### ISSUE TITLE
slash command cannot resolve attachment

### ISSUE THREAD

**Issue by ThanatosDi** [Pycord-Development/pycord#1052]
### Summary

slash command cannot resolve attachment throw except discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: 'resolved'

### Reproduction Steps

Upload attachments using slash command

### Minimal Reproducible Code

```python
class MemeCog(commands.Cog):
    meme = SlashCommandGroup("meme", "Meme(迷因)斜線命令")
    def __init__(self, bot: commands.Bot):
        self.bot = bot

    @meme.command(name='add', guild_ids=[...])
    async def _meme_add(
        self,
        ctx: discord.ApplicationContext,
        attachment: Option(discord.Attachment, "梗圖", required=True,),
    ):
        """新增梗圖命令"""
        file = await attachment.to_file()
        await ctx.respond("Here's your file!", file=file)
```

### Expected Results

correct response

### Actual Results

get except
```bash
Ignoring exception in command meme add:
Traceback (most recent call last):
  File "H:\VSCode\Python\MilaBot\.venv\lib\site-packages\discord\commands\core.py", line 110, in wrapped
    ret = await coro(arg)
    await injected(ctx)
  File "H:\VSCode\Python\MilaBot\.venv\lib\site-packages\discord\commands\core.py", line 110, in wrapped
    ret = await coro(arg)
  File "H:\VSCode\Python\MilaBot\.venv\lib\site-packages\discord\commands\core.py", line 1029, in _invoke
    await command.invoke(ctx)
  File "H:\VSCode\Python\MilaBot\.venv\lib\site-packages\discord\commands\core.py", line 306, in invoke
    await injected(ctx)
  File "H:\VSCode\Python\MilaBot\.venv\lib\site-packages\discord\commands\core.py", line 116, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: 'resolved'     
```

### Intents

130813

### System Information

- Python v3.8.10-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
This was fixed with https://github.com/Pycord-Development/pycord/commit/e7a180ea4b65307cf71154fab091c46a0b36f38c
