### ISSUE TITLE
Autocomplete doesn't work if Autocomplete function takes to long to call.

### ISSUE THREAD

**Issue by MaxOrtGit** [Pycord-Development/pycord#1071]
### Summary

If AutocompleteContext function takes too long it gets stuck repeatedly calling the function. 

### Reproduction Steps

1. Create Autocomplete function that takes a bit to get word list.
2. Put Autocomplete function in slash command option.

### Minimal Reproducible Code

```python
async def color_ac(ctx: discord.AutocompleteContext):
  color_list = get_color_from_db() #takes a while to execute method
  return color_list

@bot.command(name = "color", description = "Color image.")
async def color(ctx, color: Option(str, "Color to color",  autocomplete=color_ac)):
  #color image
```

### Expected Results

1. option in color autocompletes and you can pick color

### Actual Results

No strings show up for auto correct and the function color_ac.
If you put a print() in color_ac it shows it gets called repeatedly.
If I put the function that takes a while in multiple times (in this example get_color_from_db()) I get the error:
```
Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/bot.py", line 1028, in on_interaction
    await self.process_application_commands(interaction)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/bot.py", line 748, in process_application_commands
    return await command.invoke_autocomplete_callback(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/commands/core.py", line 1026, in invoke_autocomplete_callback
    await command.invoke_autocomplete_callback(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/commands/core.py", line 790, in invoke_autocomplete_callback
    return await ctx.interaction.response.send_autocomplete_result(choices=choices)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/interactions.py", line 780, in send_autocomplete_result
    await adapter.create_interaction_response(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/async_.py", line 211, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

### Intents

all

### System Information

- Python v3.8.12-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Linux 5.11.0-1029-gcp #33~20.04.3-Ubuntu SMP Tue Jan 18 12:03:29 UTC 2022

(I cloned it in my project yesterday)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AnimateShadows** [comment]
You only have 3 seconds to respond to an interaction.

**Comment by Dorukyum** [comment]
You shouldn't make a db request on every autocomplete call anyway. It can easily be spammed.
