### ISSUE TITLE
discord.Interaction referencing discord.ui.Button

### ISSUE THREAD

**Issue by Craftzman7** [Pycord-Development/pycord#1073]
### Summary

When I reference a property on an interaction on a button it returns discord.ui.Button

### Reproduction Steps

Simply reference a property when receiving a button event and you'll get 

```
AttributeError: 'Button' object has no attribute 'whateveryoureferenced'
```

### Minimal Reproducible Code

```python
@discord.ui.button(label="Confirm", style=discord.ButtonStyle.green)
    async def confirm(
        self, interaction: discord.Interaction, _button: discord.ui.Button
    ):
        if self.user != interaction.user:
            await interaction.response.send_message("This is not your menu", ephemeral=True)
        else:
            self.value = True
            self.stop()

@discord.ui.button(label="Cancel", style=discord.ButtonStyle.grey)
async def cancel(self, interaction: discord.Interaction, _button: discord.ui.Button):
    if self.user != interaction.user:
        await interaction.response.send_message("This is not your menu", ephemeral=True)
    else:
        self.value = False
        self.stop()
```

### Expected Results

An interaction object to be returned

### Actual Results

A button object is returned 

### Intents

discord.Intents.all()

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by krittick** [comment]
Please provide the entire traceback. Thanks!

**Comment by Craftzman7** [comment]
````
Ignoring exception in view <Confirm timeout=180.0 children=2> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=False label='Cancel' emoji=None row=None>:
Traceback (most recent call last):
  File "C:\Users\zezet\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ui\view.py", line 371, in _scheduled_task
    await item.callback(interaction)
  File "C:\Users\zezet\Desktop\dot\bot\utils\views.py", line 27, in cancel
    print(interaction.user)
AttributeError: 'Button' object has no attribute 'user'
```
