### ISSUE TITLE
ModuleNotFoundError: No module named 'chardet'

### ISSUE THREAD

**Issue by UCYT5040** [Pycord-Development/pycord#1076]
### Summary

When I run I get ModuleNotFoundError: No module named 'chardet'

### Reproduction Steps

1. Enter code from `Minimal Reproducible Code`
2. Run

### Minimal Reproducible Code

```python
from discord.ext import commands
import discord

bot = commands.Bot()

with open(".token", "r") as token:
    bot.run(token=token.read())
```

### Expected Results

I expect the bot to just go online.

### Actual Results

```
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 70, in <module>
    import cchardet as chardet
ModuleNotFoundError: No module named 'cchardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/Fight-Bot/main.py", line 1, in <module>
    from discord.ext import commands
  File "/workspace/.pip-modules/lib/python3.8/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/workspace/.pip-modules/lib/python3.8/site-packages/discord/client.py", line 33, in <module>
    import aiohttp
  File "/workspace/.pip-modules/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/workspace/.pip-modules/lib/python3.8/site-packages/aiohttp/client.py", line 58, in <module>
    from .client_reqrep import (
  File "/workspace/.pip-modules/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import chardet  # type: ignore
ModuleNotFoundError: No module named 'chardet'
gitpod /workspace/Fight-Bot (main) $ /home/gitpod/.pyenv/versions/3.8.12/bin/python /workspace/Fight-Bot/main.py
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 70, in <module>
    import cchardet as chardet
ModuleNotFoundError: No module named 'cchardet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/Fight-Bot/main.py", line 1, in <module>
    from discord.ext import commands
  File "/workspace/.pip-modules/lib/python3.8/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/workspace/.pip-modules/lib/python3.8/site-packages/discord/client.py", line 33, in <module>
    import aiohttp
  File "/workspace/.pip-modules/lib/python3.8/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/workspace/.pip-modules/lib/python3.8/site-packages/aiohttp/client.py", line 58, in <module>
    from .client_reqrep import (
  File "/workspace/.pip-modules/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 72, in <module>
    import chardet  # type: ignore
ModuleNotFoundError: No module named 'chardet'
```

### Intents

None

### System Information

This had an error so

Python 3.8
Ubuntu Linux

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
Your modules weren't installed correctly, cchardet should have been installed with aiohttp.

**Comment by UCYT5040** [comment]
When I do `pip install chardet` it says it is already installed.

**Comment by Miolus** [comment]
Reinstall pycord would also check the modules, maybe give that a try.

**Comment by BobDotCom** [comment]
`pip install aiohttp --force-reinstall` should fix this
