### ISSUE TITLE
`modal_dialogs.py` example doesn't work

### ISSUE THREAD

**Issue by Ahsoka** [Pycord-Development/pycord#1173]
### Summary

The [`modal_dialogs.py`] file does not work and errors out upon running the file.

### Reproduction Steps

Just run [`modal_dialogs.py`] and it errors out.

### Expected Results

It should work.

### Actual Results

```py
Traceback (most recent call last):
  File "modals.py", line 54, in <module>
    async def modaltest(ctx):
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\bot.py", line 834, in decorator
    result = command(**kwargs)(func)
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\commands\core.py", line 1464, in decorator
    return cls(func, **attrs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\commands\core.py", line 575, in __init__
    validate_chat_input_description(description)
  File "C:\ProgramData\Anaconda3\lib\site-packages\discord\commands\core.py", line 1507, in validate_chat_input_description
    raise ValidationError(
discord.errors.ValidationError: Command description must be 1-100 characters long. Received Shows an example of modals being invoked from an interaction component (e.g. a button or select menu)
```

### Intents

Intents are not relevant here

### System Information

Python Version: 3.9.7
OS: Windows 10
Pycord Version: 2.0.0b4

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

[`modal_dialogs.py`]: https://github.com/Pycord-Development/pycord/blob/master/examples/modal_dialogs.py

**Comment by Snawe** [comment]
can you check 2.0.0b5? I don't see it here

**Comment by Middledot** [comment]
Cannot reproduce in 2.0.0b4 or 2.0.0b5. This seems it would only happen if you replaced `commands.Bot` with `discord.Bot`
