### ISSUE TITLE
slash_cog.py example does not work for me

### ISSUE THREAD

**Issue by bitfl0wer** [Pycord-Development/pycord#1195]
### Summary

The Example seems to be outdated in some way shape or form

### Reproduction Steps

- Created a Python 3.8.10 venv with the following pip packages installed:
`aiohttp==3.7.4.post0
async-timeout==3.0.1
attrs==21.4.0
autopep8==1.6.0
chardet==4.0.0
idna==3.3
multidict==6.0.2
py-cord==1.7.3
pycodestyle==2.8.0
toml==0.10.2
typing-extensions==4.1.1
yarl==1.7.2`

- Tried to copy the code into my project
- The first line already did not work. The code attached in the 'Minimal Reproducible Code' results in the following error: 
![grafik](https://user-images.githubusercontent.com/39242991/159808157-abbaf72d-1484-433c-a61e-62dfbc83348f.png)
and the bot will not start due to this issue. Console output: `(venv) starflower@element:~/Dokumente/Codespaces/magicaltavern$  cd /home/starflower/Dokumente/Codespaces/magicaltavern ; /usr/bin/env /home/starflower/Dokumente/Codespaces/magicaltavern/venv/bin/python /home/starflower/.vscode/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/launcher 44553 -- /home/starflower/Dokumente/Codespaces/magicaltavern/src/bot.py 
Traceback (most recent call last):
  File "/home/starflower/Dokumente/Codespaces/magicaltavern/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/starflower/Dokumente/Codespaces/magicaltavern/src/commands/utility.py", line 3, in <module>
    from discord.commands import (
ModuleNotFoundError: No module named 'discord.commands'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/starflower/.vscode/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/starflower/.vscode/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/starflower/.vscode/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/starflower/Dokumente/Codespaces/magicaltavern/src/bot.py", line 14, in <module>
    bot.load_extension("commands.utility")
  File "/home/starflower/Dokumente/Codespaces/magicaltavern/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 678, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/starflower/Dokumente/Codespaces/magicaltavern/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'commands.utility' raised an error: ModuleNotFoundError: No module named 'discord.commands'`

### Minimal Reproducible Code

```python
from discord.commands import (
    slash_command,
)
```

### Expected Results

I expected that the import works

### Actual Results

...it doesn't

### Intents

none

### System Information

`(venv) starflower@element:~/Dokumente/Codespaces/magicaltavern$ python -m discord -v
- Python v3.8.10-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.17.0-051700-generic #202203202130 SMP PREEMPT Sun Mar 20 21:33:41 UTC 2022`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I want to know if this is a me-issue, or if something is outdated/not working anymore.

**Comment by EmreTech** [comment]
And there's your issue. You're using py-cord 1.7.3, not py-cord 2.0.0.

**Comment by BobDotCom** [comment]
`pip install py-cord~=2.0.0b5`

**Comment by bitfl0wer** [comment]
Thank you for clearing that up - However, I am still a bit confused as to why this is the case. I may have just not seen it, but it would be nice to hint at the fact that you need to use the pre-release version of the package to follow the examples. Then again - It was very late for me in the evening and I have been looking at different parts of the docs for an hour or so, I may have just not seen it. My apologies for the inconvenience.
