### ISSUE TITLE
Cannot import InputText from discord.ui

### ISSUE THREAD

**Issue by Fallcrim** [Pycord-Development/pycord#1266]
### Summary

I am not able to import InputText from discord.ui

### Reproduction Steps

Use the following line of code
`from discord.ui import InputText`

### Expected Results

The code should run smoothly as always. Means no ImportErrors

### Actual Results

I got an error which says that I can't import InputText from discord.ui
`Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\cog.py", line 657, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Me\Desktop\Python Code Projekte\AllRounder\cogs\general.py", line 5, in <module>
    from discord.ui import InputText, Modal
ImportError: cannot import name 'InputText' from 'discord.ui' (C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ui\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Me\Desktop\Python Code Projekte\AllRounder\main.py", line 9, in <module>
    bot.load_extension(f"cogs.{cog[:-3]}")
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\cog.py", line 729, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\cog.py", line 660, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'cogs.general' raised an error: ImportError: cannot import name 'InputText' from 'discord.ui' (C:\Users\Me\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ui\__init__.py)`

### Intents

`discord.Intents.all()`

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by krittick** [comment]
You're using an older version of pycord before modals and input text fields were added. Please uninstall and then reinstall the latest beta release via `pip install --pre py-cord`
