### ISSUE TITLE
Defering a response interfares with being able to send a modal.

### ISSUE THREAD

**Issue by GamingGuyLV** [Pycord-Development/pycord#1322]
### Summary

In a slash command after deferring the interaction, if you try sending a modal it spits out an error saying that interaction has already been responed to.

### Reproduction Steps

1) create modal
2) create simple slash command
3) await ctx.defer() at the start of slash command
4) await ctx.send_modal(modal) somewhere later
5) Boom, error, profit

### Minimal Reproducible Code

```python
class MyModal(discord.ui.Modal):
  def __init__(self) -> None:
    super().__init__("My modal")
    self.add_item(discord.ui.InputText(label="ShortText", style=discord.InputTextStyle.short))
  async def callback(self, interaction: discord.Interaction):
    await interaction.response.send_message("Modal received")
    self.stop()

@bot.slash_command()
async def defermodal(ctx):
  await ctx.defer()
  modal = MyModal()
  await ctx.send_modal(modal)
```

### Expected Results

A popup modal with "MyModal" as title and a short text input box.

Afterwards a response saying "Modal received".

### Actual Results

Traceback (most recent call last):
  File "C:\Users\GamingGuyLV\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 122, in wrapped
    ret = await coro(arg)
  File "C:\Users\GamingGuyLV\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 839, in _invoke
    await self.callback(ctx, **kwargs)
  File "e:\VS Code\Discordbot\Main.py", line 1227, in createbet
    await ctx.send_modal(modal)
  File "C:\Users\GamingGuyLV\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\interactions.py", line 824, in send_modal
    raise InteractionResponded(self._parent)
discord.errors.InteractionResponded: This interaction has already been responded to before

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\GamingGuyLV\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\bot.py", line 1103, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "C:\Users\GamingGuyLV\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 345, in invoke
    await injected(ctx)
  File "C:\Users\GamingGuyLV\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 128, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: InteractionResponded: This interaction has already been responded to before

### Intents

All

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.8.1
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
Discord doesn't allow you to send an interaction response more than once; and deferring is considered a response.
