### ISSUE TITLE
@on_command_error isnt working with application commands

### ISSUE THREAD

**Issue by PolyTree18** [Pycord-Development/pycord#1338]
### Summary

the error listener is not called when an error occurs in the application command

### Reproduction Steps

1. Write an application(slash) command in cog(example in minimal reproducible code)
2. write an error handler in another cog
3. in command, try, for example, convert invalid emoji with discord.ext.commands.EmojiConverter
4. in discord\commands\core.py" change line 119 to raise exc. (so that instead of discord.commands.errors.ApplicationCommandInvokeError, the EmojiNotFound error is raised)

### Minimal Reproducible Code

```python
#_test/cogs/errors.py

class ErrorHandler(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def on_command_error(self, ctx, error):
        if ctx.command.has_error_handler:
            return
        cog = ctx.cog
        if cog:
            if cog._get_overridden_method(cog.cog_command_error) is not None:
                return
        ignored = (commands.CommandNotFound, commands.CheckFailure)
        error = getattr(error, 'original', error)
        if isinstance(error, ignored):
            return
        if isinstance(error, commands.EmojiNotFound):
            text = "emoji not found"
        else:
            text = "unhandled error"
        if ctx.message:
            return await ctx.send(content=text)
        else:
            return await ctx.followup.send(content=text)

def setup(bot):
    bot.add_cog(FindEmojiCmd(bot))
```

```python
#_test/cogs/findemoji.py

class FindEmojiCmd(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.emoji_converter = commands.EmojiConverter()

    @discord.slash_command()
    async def find_emoji(self, ctx,
        emoji: discord.Option(str, "Emoji to find", name="emoji", required=True)
    ):
        await ctx.response.defer()
        await self.emoji_converter.convert(ctx, emoji)
        await ctx.followup.send(emoji.name)

def setup(bot):
    bot.add_cog(FindEmojiCmd(bot))
```

```python
#_test/bot.py

bot = commands.AutoShardedBot(command_prefix = ">>", intents=discord.Intents.all())
bot.remove_command("help")
if __name__ == "__main__":
    for extension in ["findemoji", "errors"]:
        bot.load_extension("cogs."+extension)
bot.run(Token, reconnect=True)
```

### Expected Results

a message with "emoji not found" in content

### Actual Results

Traceback:

```
Ignoring exception in command find_emoji:
Traceback (most recent call last):
  File "E:\Python\Python39\lib\site-packages\discord\commands\core.py", line 113, in wrapped
    ret = await coro(arg)
  File "E:\Python\Python39\lib\site-packages\discord\commands\core.py", line 764, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "E:\documents\GitHub\_test_\Main\Modules\Utils\reactionroles.py", line 72, in find_emoji
    await self.emoji_converter.convert(ctx, emoji)
  File "E:\Python\Python39\lib\site-packages\discord\ext\commands\converter.py", line 809, in convert
    raise EmojiNotFound(argument)
discord.ext.commands.errors.EmojiNotFound: Emoji "zvcx" not found.
```

### Intents

discord.Intents.all()

### System Information

- Python v3.9.5-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.8.1
- system info: Windows 10 10.0.21390

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

**there is no additional context**, and im sorry if i wrote something wrong

**Comment by joksulainen** [comment]
not an issue. application command errors are handled by on_application_command_error event

**Comment by PolyTree18** [comment]
sorry, i didnt see it
