### ISSUE TITLE
_check_required_params appears incorrect

### ISSUE THREAD

**Issue by bpafoshizle** [Pycord-Development/pycord#1342]
### Summary

The _check_required_params does not appear to really check and fails when params are present

### Reproduction Steps

- Create a class that extends commands.Cog
- Create an async method with self and ctx parameters
- Add the coroutine method using `slash_command` method from ApplicationCommandMixin in bot.py
- Create a bot using discord.ext.commands.bot
- Add cog class to bot using `add_cog`

### Minimal Reproducible Code

```python
from discord.ext import commands

class MyClass(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        bot.slash_command()(self.my_command_method)

    async def my_command_method(self, ctx):
        await ctx.respond("testing")

if __name__ == "__main__":
    bot = commands.Bot()
    bot.add_cog(MyClass(bot))
```

### Expected Results

I expect the bot to be created, which was the behavior prior to commit 6913833c1e076b9c14e7a51ceeb1ff4c156e9164.

It's also not clear to me that the check is robust. Isn't it simply checking that there are at most two parameters, but not the correct parameters? 

### Actual Results

```(venv) ➜  pycord-testing git:(main) ✗ python myclass.py
self.attached_to_group: False
self.cog: None
self.callback.__qualname__: MyClass.my_command_method
len(self.callback.__qualname__.split('.')): 2
required_params: ['self', 'context']
p: self
next(params): ('ctx', <Parameter "ctx">)
p: context
Traceback (most recent call last):
  File "/Users/bpafoshizle/github/local/fwm-bot/venv/src/py-cord/discord/commands/core.py", line 674, in _check_required_params
    print(f"next(params): {next(params)}")
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bpafoshizle/github/local/fwm-bot/pycord-testing/myclass.py", line 13, in <module>
    bot.add_cog(MyClass(bot))
  File "/Users/bpafoshizle/github/local/fwm-bot/pycord-testing/myclass.py", line 6, in __init__
    bot.slash_command()(self.my_command_method)
  File "/Users/bpafoshizle/github/local/fwm-bot/venv/src/py-cord/discord/bot.py", line 813, in decorator
    result = command(**kwargs)(func)
  File "/Users/bpafoshizle/github/local/fwm-bot/venv/src/py-cord/discord/commands/core.py", line 1584, in decorator
    return cls(func, **attrs)
  File "/Users/bpafoshizle/github/local/fwm-bot/venv/src/py-cord/discord/commands/core.py", line 644, in __init__
    self.options: List[Option] = self._parse_options(params)
  File "/Users/bpafoshizle/github/local/fwm-bot/venv/src/py-cord/discord/commands/core.py", line 682, in _parse_options
    params = self._check_required_params(params)
  File "/Users/bpafoshizle/github/local/fwm-bot/venv/src/py-cord/discord/commands/core.py", line 676, in _check_required_params
    raise ClientException(f'Callback for {self.name} command is missing "{p}" parameter.')
discord.errors.ClientException: Callback for my_command_method command is missing "context" parameter.```

### Intents

I am not using intents to reproduce this

### System Information

- Python v3.9.9-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b7
- aiohttp v3.8.1
- system info: Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

**Comment by Dorukyum** [comment]
This is not the intended way of creating a command inside a cog. Please view the [cogs example](https://github.com/Pycord-Development/pycord/blob/master/examples/app_commands/slash_cog.py).

> Isn't it simply checking that there are at most two parameters, but not the correct parameters?

The parameter names might differ so checking the parameter count is the way to go here.

**Comment by bpafoshizle** [comment]
@Dorukyum thanks for the reply and example! The reason I have been creating slash commands in the manner I do above, is because I am attempting to build a bot_builder class that will read a yaml configuration file at runtime with properties for my cogs, including guild_ids they should be set up for. At runtime the classes will be instantiated, and the guild_ids passed in. Since decorators are evaluated at class parse time, I cannot seem to figure out another better way to dynamically pass in the needed guild_ids at runtime. Trying to do something like this, if it makes it clearer. This doesn't work, because self is not accessible to the decorator: 


```
import os
import discord
from discord.commands import (  # Importing the decorator that makes slash commands.
    slash_command,
    option
)
from discord.ext import commands

class MyClass(commands.Cog):
    def __init__(self, bot, guild_ids):
        self.bot = bot
        self.guild_ids = guild_ids
    
    @slash_command(guild_ids=self.guild_ids)  # Create a slash command for the supplied guilds.
    async def hello(
        self,
        ctx
    ):
        await ctx.respond(f"Hello!")

if __name__ == "__main__":
    bot = commands.Bot()
    bot.add_cog(MyClass(bot, os.getenv("DISCORD_GUILD_ID")))
    bot.run(os.getenv('DISCORD_TOKEN'))
```

**Comment by bpafoshizle** [comment]
If anyone else stumbles upon this thread and needs to be able to dynamically create slash commands without hard-coded guild IDs in the code or environment variables, this works. It's ugly, but it works: 

```python
import os
import logging
from discord.ext import commands

logger = logging.getLogger(__name__)

class MyClass(commands.Cog):
    def __init__(self, bot, guild_ids):
        self.bot = bot
        self.guild_ids = guild_ids
        bot.slash_command()(self.my_command_method)

    async def my_command_method(self, ctx, dorukyumParam="https://github.com/Pycord-Development/pycord/issues/1342"):
        logger.debug(f"reason for the dorukyumParam: {dorukyumParam}")
        await ctx.respond(f"Hello from my_command_method!")


if __name__ == "__main__":
    bot = commands.Bot()
    bot.add_cog(MyClass(bot, os.getenv("DISCORD_GUILD_ID")))
    bot.run(os.getenv('DISCORD_TOKEN'))
```
