### ISSUE TITLE
class CeilTimeout invalid function use

### ISSUE THREAD

**Issue by galaxine-senpai** [Pycord-Development/pycord#1470]
### Summary

Upon running my bot an error came up saying something along the lines of "TypeError: function() argument 'code' must be code, not str"

### Reproduction Steps

Unknown as far as I know

### Minimal Reproducible Code

```python
This happens upon using the package period

Here is my traceback of the incident:

ayden@microwave:~/microwave $ python3 index.py
Traceback (most recent call last):
  File "/home/ayden/microwave/index.py", line 2, in <module>
    import discord
  File "/home/ayden/.local/lib/python3.9/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/home/ayden/.local/lib/python3.9/site-packages/discord/client.py", line 33, in <module>
    import aiohttp
  File "/home/ayden/.local/lib/python3.9/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/home/ayden/.local/lib/python3.9/site-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/home/ayden/.local/lib/python3.9/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/home/ayden/.local/lib/python3.9/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/home/ayden/.local/lib/python3.9/site-packages/aiohttp/helpers.py", line 667, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
```

### Expected Results

Everything to work as normal

### Actual Results

The class "CeilTimeout" returns an error

### Intents

N/A (Not needed for this as it is the package it's self)

### System Information

OS: Debian GNU/Linux 11 (bullseye) aarch64
Host: Raspberry Pi 4 Model B Rev 1.1 
Kernel: Kernel: 5.15.32-v8+

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Edit: this appears to be an aiohttp problem upon further inspection of the traceback

**Comment by galaxine-senpai** [comment]
It is an aiohttp problem, a simple update fixed it
