### ISSUE TITLE
ext.pages message is none if "View Channel" permissions are missing

### ISSUE THREAD

**Issue by Snawe** [Pycord-Development/pycord#1500]
### Summary

If the bot does not have "View Channel" permissions, exceptions are not catched

### Reproduction Steps

```py    
    @slash_command()
    async def test(self, ctx):
        await ctx.defer() # Note: The defer is needed! Otherwise it works
        page_groups = []
        page_groups.append(pages.PageGroup(pages="1", label="label 1"))
        page_groups.append(pages.PageGroup(pages="2", label="label 2"))
        paginator = pages.Paginator(pages=page_groups, show_disabled=False, show_menu=True)
        await paginator.respond(ctx.interaction, ephemeral=False)
```

### Expected Results

That it should either work (like without `defer`) or catch the exception :)

### Actual Results

On `/test` you get:
```
Ignoring exception in command test:
Traceback (most recent call last):
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\commands\core.py", line 127, in wrapped
    ret = await coro(arg)
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\commands\core.py", line 877, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "g:\develop\bot\cogs\stuff.py", line 403, in test
    await paginator.respond(ctx.interaction, ephemeral=False)
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\ext\pages\pagination.py", line 1068, in respond
    msg = await msg.channel.fetch_message(msg.id)
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\abc.py", line 1601, in fetch_message
    data = await self._state.http.get_message(channel.id, id)
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\http.py", line 354, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\bot.py", line 992, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\commands\core.py", line 358, in invoke
    await injected(ctx)
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\commands\core.py", line 135, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

and when you select an other item in the dropdown you get 
```
Ignoring exception in view <Paginator timeout=180.0 children=2> for item <PaginatorMenu placeholder='Select Page Group' min_values=1 max_values=1 options=[<SelectOption label='label 1' value='label 1' description=None emoji=None default=False>, <SelectOption label='label 2' value='label 2' description=None emoji=None default=False>] disabled=False>:
Traceback (most recent call last):
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\ui\view.py", line 375, in _scheduled_task
    await item.callback(interaction)
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\ext\pages\pagination.py", line 1150, in callback
    return await self.paginator.update(
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\ext\pages\pagination.py", line 522, in update
    await self.goto_page(self.current_page, interaction=interaction)
  File "g:\develop\bot\venv_pycord\lib\site-packages\discord\ext\pages\pagination.py", line 630, in goto_page
    message_id=self.message.id,
AttributeError: 'NoneType' object has no attribute 'id'
```

### Intents

default

### System Information

- Python v3.9.4-final
- py-cord v2.0.0-final
- aiohttp v3.7.3

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by SuicideParty** [comment]
Message intent?  And where is Custom_id thats used to pass interaction?
