### ISSUE TITLE
Passing `discord.Emoji` as `input_type` in `discord.commands.Option` raises `TypeError`

### ISSUE THREAD

**Issue by SandeepKanekal** [Pycord-Development/pycord#1506]
### Summary

When trying to accept an emoji as an argument from discord, using slash commands, `EmojiConverter.convert()` raises `TypeError` with the message: `EmojiConverter.convert() missing 1 required positional argument: 'argument'`

### Reproduction Steps

Create an option parameter in a slash command with `input_type` as `discord.Emoji`.

### Minimal Reproducible Code

```python
@commands.slash_command(name='test', guild_ids=[930715526441885696])
async def test(self, ctx, emoji: Option(discord.Emoji, description='Enter an emoji', required=True)):
    pass
```

### Expected Results

Accept a parameter of type `discord.Emoji`

### Actual Results

An error is raised
```

Ignoring exception in command test:
Traceback (most recent call last):
  File "C:\Users\sande\AppData\Roaming\Python\Python310\site-packages\discord\commands\core.py", line 127, in wrapped
    ret = await coro(arg)
  File "C:\Users\sande\AppData\Roaming\Python\Python310\site-packages\discord\commands\core.py", line 851, in _invoke
    arg = await converter.convert(ctx, arg)
TypeError: EmojiConverter.convert() missing 1 required positional argument: 'argument'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sande\AppData\Roaming\Python\Python310\site-packages\discord\bot.py", line 992, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "C:\Users\sande\AppData\Roaming\Python\Python310\site-packages\discord\commands\core.py", line 358, in invoke
    await injected(ctx)
  File "C:\Users\sande\AppData\Roaming\Python\Python310\site-packages\discord\commands\core.py", line 135, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: TypeError: EmojiConverter.convert() missing 1 required positional argument: 'argument'

```

### Intents

discord.Intents.all()

### System Information

- Python v3.10.5-final
- py-cord v2.0.0-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
Emoji is no valid application command option
