### ISSUE TITLE
commands.has_permissions() decorator dont work correctly in DM channels

### ISSUE THREAD

**Issue by yoggys** [Pycord-Development/pycord#1576]
### Summary

commands.has_permissions() decorator dont work correctly in DM channels

### Reproduction Steps

- Create command with @commands.has_permissions() decorator
- Try to use command in DM Channel

### Minimal Reproducible Code

```python
from discord.ext import commands
...

@commands.slash_command()
@commands.has_permissions(manage_guild=True)
async def test(self, ctx: discord.ApplicationContext:
    pass
```

### Expected Results

has_permissions should return True while using commands/slash commands in DM channel:
```If the command is executed within a DM, it returns "True".``` [(link)](https://github.com/Pycord-Development/pycord/blob/e0d4c4549a7706fd9966745e64a464a27d3da21f/discord/ext/commands/core.py#L2095)

### Actual Results

```bash
Ignoring exception in on_interaction
Traceback (most recent call last):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\bot.py", line 1043, in on_interaction
    await self.process_application_commands(interaction)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\bot.py", line 738, in process_application_commands
    await self.invoke_application_command(ctx)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\bot.py", line 994, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 355, in invoke
    await self.prepare(ctx)
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 277, in prepare
    if not await self.can_run(ctx):
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 374, in can_run
    return await async_all(predicate(ctx) for predicate in predicates)  # type: ignore
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\utils.py", line 562, in async_all
    for elem in gen:
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 374, in <genexpr>
    return await async_all(predicate(ctx) for predicate in predicates)  # type: ignore
  File "C:\Users\*\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 2120, in predicate
    permissions = ch.permissions_for(ctx.author)  # type: ignore
AttributeError: 'PartialMessageable' object has no attribute 'permissions_for
```

### Intents

```py
discord.Intents.all()
```

### System Information

```bash
- Python v3.8.13-final
- py-cord v2.1.0-final
- aiohttp v3.8.1
- system info: Linux 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

https://discordpy.readthedocs.io/en/latest/interactions/api.html#discord.Interaction.channel

Note that due to a Discord limitation, DM channels are not resolved since there is no data to complete them. 
These are [PartialMessageable](https://discordpy.readthedocs.io/en/latest/api.html#discord.PartialMessageable) instead.

**Comment by EmreTech** [comment]
Because it's a DM Channel? DM Channels have 0 permissions
