### ISSUE TITLE
`discord.Emoji` and `discord.PartialEmoji` didn't work in slash option.

### ISSUE THREAD

**Issue by Sodynoizz** [Pycord-Development/pycord#1582]
### Summary

The slash command didn't work when I add slash option which contains `Union[discord.Emoji, discord.PartialEmoji]` type 

### Reproduction Steps

I tested code that has attribute type `Union[discord.Emoji, discord.PartialEmoji]` and this command didn't synced with guilds.

### Minimal Reproducible Code

```python
@discord.commands.slash_command(name="test")
async def emoji(self, ctx: discord.ApplicationContext, emoji : Union[discord.Emoji, discord.PartialEmoji]):
        await ctx.respond(emoji.name)
```

### Expected Results

I want the slash option support for `discord.Emoji` and `discord.PartialEmoji`

### Actual Results

The command didn't synced with guilds.

### Intents

intents = discord.Intents.all()

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by EmreTech** [comment]
`discord.Emoji` is not a valid option type.

**Comment by Dorukyum** [comment]
Can you try using only `discord.Emoji`, this should use the converter

**Comment by Sodynoizz** [comment]
> Can you try using only `discord.Emoji`, this should use the converter

Code that I tested
```python
@discord.commands.slash_command(name="test")
async def emoji(self, ctx: discord.ApplicationContext, emoji : discord.Emoji):
        await ctx.respond(emoji.name)
```

I got this error
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: TypeError: EmojiConverter.convert() missing 1 required positional argument: 'argument'

**Comment by yoggys** [comment]
> Can you try using only `discord.Emoji`, this should use the converter

```py
from discord.ext.commands import Converter
isinstance(Converter, type)
isinstance(Converter, Converter)

# both return true so it fails at first if (not initialized)
if isinstance(converter, Converter):
    arg = await converter.convert(ctx, arg)
elif isinstance(converter, type) and hasattr(converter, "convert"):
    arg = await converter().convert(ctx, arg)
```

**Comment by plun1331** [comment]
This should be fixed in the latest release

**Comment by Sodynoizz** [comment]
> This should be fixed in the latest release

Well, I tested that code in py-cord version 2.1.1 with 1️⃣ emoji but it raised this error
```
discord.ext.commands.errors.EmojiNotFound: Emoji "1️⃣" not found.
```

**Comment by plun1331** [comment]
> > This should be fixed in the latest release
> 
> Well, I tested that code in py-cord version 2.1.1 with 1️⃣ emoji but it raised this error
> ```
> discord.ext.commands.errors.EmojiNotFound: Emoji "1️⃣" not found.
> ```

Try with a custom emoji, 1️⃣ is technically only a unicode character and not considered an emoji by the parser.

**Comment by Caraffa-git** [comment]
Hi, I have related but not the same problem with Emojis.

I made dropdown menu that user can customize with commands. I didn't found any proper way to pass unicode emoji through command. But why would I need a unicode emoji, you might ask? Because  `discord.SelectOption` doesn't like standard discord emoji format (e.g. `:bulb`), it works with unicode just fine. **It also has no problem with cusotm emojis for some reason.**

Error message that i get:
```
Traceback (most recent call last):
  File "/home/rafaln/.local/lib/python3.10/site-packages/discord/bot.py", line 1114, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/rafaln/.local/lib/python3.10/site-packages/discord/commands/core.py", line 375, in invoke
    await injected(ctx)
  File "/home/rafaln/.local/lib/python3.10/site-packages/discord/commands/core.py", line 132, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.components.0.components.0.options.0.emoji.name: Invalid emoji
```
I used [this example](https://github.com/Pycord-Development/pycord/blob/master/examples/views/dropdown.py) and modified it a little bit:

```
options = [
            discord.SelectOption(
                label="Red", description="Your favourite colour is red", emoji=":smile:"
            ),
            discord.SelectOption(
                label="Green", description="Your favourite colour is green", emoji="⚗"
            ),
            discord.SelectOption(
                label="Blue", description="Your favourite colour is blue", emoji="<:troll:910540961958989934>"
            ),
```

**Comment by Paillat-dev** [comment]
What is the issue here ?

**Comment by Lumabots** [comment]
i'll fix that toonight

**Comment by Lumabots** [comment]
#2814

**Comment by Paillat-dev** [comment]
@Lulalaby Can you reopen this ?

**Comment by Paillat-dev** [comment]
#2815 does NOT fix this

**Comment by Lumabots** [comment]
> Hi, I have related but not the same problem with Emojis.
> 
> I made dropdown menu that user can customize with commands. I didn't found any proper way to pass unicode emoji through command. But why would I need a unicode emoji, you might ask? Because `discord.SelectOption` doesn't like standard discord emoji format (e.g. `:bulb`), it works with unicode just fine. **It also has no problem with cusotm emojis for some reason.**
> 
> Error message that i get:
> 
> ```
> Traceback (most recent call last):
>   File "/home/rafaln/.local/lib/python3.10/site-packages/discord/bot.py", line 1114, in invoke_application_command
>     await ctx.command.invoke(ctx)
>   File "/home/rafaln/.local/lib/python3.10/site-packages/discord/commands/core.py", line 375, in invoke
>     await injected(ctx)
>   File "/home/rafaln/.local/lib/python3.10/site-packages/discord/commands/core.py", line 132, in wrapped
>     raise ApplicationCommandInvokeError(exc) from exc
> discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
> In data.components.0.components.0.options.0.emoji.name: Invalid emoji
> ```
> 
> I used [this example](https://github.com/Pycord-Development/pycord/blob/master/examples/views/dropdown.py) and modified it a little bit:
> 
> ```
> options = [
>             discord.SelectOption(
>                 label="Red", description="Your favourite colour is red", emoji=":smile:"
>             ),
>             discord.SelectOption(
>                 label="Green", description="Your favourite colour is green", emoji="⚗"
>             ),
>             discord.SelectOption(
>                 label="Blue", description="Your favourite colour is blue", emoji="<:troll:910540961958989934>"
>             ),
> ```

#2815 should fix this, but not the first comment

**Comment by Lumabots** [comment]
this is no longer an issue when using GuildEmoji or PartialConverter.  The support of the union doesnt work but it should be a feature and not a bug
