### ISSUE TITLE
create_group not working

### ISSUE THREAD

**Issue by Totally-Real-Penguin** [Pycord-Development/pycord#1617]
### Summary

using create_group just creates a massive error

### Reproduction Steps

I put my guild id in debug_guilds
and put my token in token
and ran it

### Minimal Reproducible Code

```python
from discord import *

bot = Bot(debug_guilds=GUILDS)

# If you use commands.Bot, @bot.slash_command should be used for
# slash commands. You can use @bot.slash_command with discord.Bot as well.

math = bot.create_group("math", "Commands related to mathematics.")  # Create a slash command group


@math.command()  # Create a slash command under the math group
async def add(ctx: ApplicationContext, num1: int, num2: int):
    """Get the sum of 2 integers."""
    await ctx.respond(f"The sum of these numbers is **{num1+num2}**")


bot.run('TOKEN')
```

### Expected Results

/math add

adds the two numbers together

### Actual Results

/math add appears but does not function

It gives me this error

Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 127, in wrapped
    ret = await coro(arg)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 1202, in _invoke
    await command.invoke(ctx)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 356, in invoke
    await self.prepare(ctx)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 278, in prepare
    if not await self.can_run(ctx):
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 373, in can_run
    local_check = cog._get_overridden_method(cog.cog_check)
AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/bot.py", line 997, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 359, in invoke
    await injected(ctx)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 135, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/bot.py", line 1046, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/bot.py", line 741, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/bot.py", line 1001, in invoke_application_command
    await ctx.command.dispatch_error(ctx, exc)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 401, in dispatch_error
    local = cog.__class__._get_overridden_method(cog.cog_command_error)
AttributeError: type object '_MissingSentinel' has no attribute '_get_overridden_method'
Ignoring exception in command math add:
Traceback (most recent call last):
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 127, in wrapped
    ret = await coro(arg)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 1202, in _invoke
    await command.invoke(ctx)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 356, in invoke
    await self.prepare(ctx)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 278, in prepare
    if not await self.can_run(ctx):
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 373, in can_run
    local_check = cog._get_overridden_method(cog.cog_check)
AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/bot.py", line 997, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 359, in invoke
    await injected(ctx)
  File "/home/penguino/.local/lib/python3.9/site-packages/discord/commands/core.py", line 135, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'

### Intents

I'm not using client im using discord.Bot()

### System Information

- Python v3.9.2-final
- py-cord v2.1.1-final

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I'm on a chromebook running it through the linux virtual machine

**Comment by Jemeni11** [comment]
I had a similar problem except I was using Python v3.8

Try using `SlashCommandGroup` instead.
And maybe downgrade to Pycord v2.0.1

```python
from discord import SlashCommandGroup

# The basic bot instance in a separate file should look something like this:
intents = discord.Intents.default()
bot = discord.Bot(debug_guilds=[...])  # specify the guild IDs in debug_guilds


@bot.command(description="Gets metadata .")  # this decorator makes a slash command
async def ping(ctx):  # a slash command will be created with the name "ping"
    await ctx.respond(f"Pong! Latency is {bot.latency}")


math = SlashCommandGroup("math", "Math related commands")


@math.command(name="add", description="+")
async def add(ctx, num1: discord.Option(int), num2: discord.Option(int)):
    sum = num1 + num2
    await ctx.respond(f"{num1} plus {num2} is {sum}.")

```
![pic](https://github.com/Jemeni11/hosting-pics/blob/main/discord.png?raw=true)

**Comment by Totally-Real-Penguin** [comment]
Sorry I don't check my mail much but i'll try that hopeful it will work

**Comment by obiwankennedy** [comment]
this commit gives a bit of the solution: a2b1d8f8316c133ff58fa7928d1a7c36948a8f79

https://github.com/Pycord-Development/pycord/commit/0a928bebc38e4b063d0a9048f4f6c72e4d6a8a92


As far as I understood. They change the default type of cog member in commands. 
Before it was None and now it is MISSING. 
But there are few tests in the class that only check if cog is not NONE. I add test to check it if is not None and not MISSING. 
and it works now. 


Example: 
```
cog = self.cog

        if cog is not None and cog is not MISSING :
            local_check = cog._get_overridden_method(cog.cog_check)
```

**Comment by Lulalaby** [comment]
Fixed in the latest version
