### ISSUE TITLE
Can't set custom name for bridge group

### ISSUE THREAD

**Issue by Krutyi-4el** [Pycord-Development/pycord#1628]
### Summary

`@bridge_group(name="name")` gives error

### Reproduction Steps

Create bridge group with a `name=`

### Minimal Reproducible Code

```python
@bot.bridge_group(name="test")
async def _test(ctx):
    await ctx.respond("aaa")
```

### Expected Results

Command registration

### Actual Results

```py
Traceback (most recent call last):
  File "D:\coding\DandelionMusic\run.py", line 37, in <module>
    async def _test(ctx):
  File "D:\coding\dandelion_env\lib\site-packages\discord\ext\bridge\bot.py", line 88, in decorator
    result = bridge_group(**kwargs)(func)
  File "D:\coding\dandelion_env\lib\site-packages\discord\ext\bridge\core.py", line 329, in decorator
    return BridgeCommandGroup(callback, **kwargs)
  File "D:\coding\dandelion_env\lib\site-packages\discord\ext\bridge\core.py", line 280, in __init__
    self.slash_variant: BridgeSlashGroup = BridgeSlashGroup(callback, self.ext_variant.name, *args, **kwargs)
  File "D:\coding\dandelion_env\lib\site-packages\discord\ext\bridge\core.py", line 88, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got multiple values for argument 'name'
```

### Intents

default + message_content

### System Information

- Python v3.9.9-final
- py-cord v2.1.3-final
- aiohttp v3.8.1
- system info: Windows 10 10.0.17763

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Krutyi-4el** [comment]
Sorry to say, but the bug remains in Pycord 2.4.0
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/data/com.termux/files/home/DandelionMusic/musicbot/__main__.py", line 40, in <module>
    @bot.bridge_group(name="test")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/bridge/bot.py", line 103, in decorator
    result = bridge_group(**kwargs)(func)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/bridge/core.py", line 386, in decorator
    return BridgeCommandGroup(callback, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/bridge/core.py", line 321, in __init__
    slash_variant=BridgeSlashGroup(callback, ext_var.name, *args, **kwargs),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/tests/lib/python3.11/site-packages/discord/ext/bridge/core.py", line 105, in __init__
    super().__init__(*args, **kwargs)
TypeError: SlashCommandGroup.__init__() got multiple values for argument 'name'
```

**Comment by JustaSqu1d** [comment]
I cannot reproduce this.

**Comment by Krutyi-4el** [comment]
Here's the full reproduction code just in case
```
import discord
from discord.ext import bridge


bot = bridge.Bot()


@bot.bridge_group(name="test")
async def _test(ctx):
    await ctx.respond("aaa")
```

**Comment by JustaSqu1d** [comment]
> Here's the full reproduction code just in case
> 
> ```
> import discord
> from discord.ext import bridge
> 
> 
> bot = bridge.Bot()
> 
> 
> @bot.bridge_group(name="test")
> async def _test(ctx):
>     await ctx.respond("aaa")
> ```

Still can't reproduce.
