### ISSUE TITLE
Select does not have a attribute children

### ISSUE THREAD

**Issue by ItsNeil17** [Pycord-Development/pycord#1645]
### Summary

A view with a select seems to not have any attribute "children"

### Reproduction Steps

I made a view with a select and for the callback, I just print `select.values[0]`

### Minimal Reproducible Code

```python
class MyView(discord.ui.View):
    
    @discord.ui.select( 
        placeholder = "Choose a Option!", 
        min_values = 1, 
        max_values = 1,
        options = [
            discord.SelectOption(
                label="Option 1",
                description="This is option 1!"
            )
        ]
    )
    async def select_callback(self, select, interaction):
        print(select.values[0])
```

### Expected Results

The view to be posted normally without raising "AttributeError"

### Actual Results

It ends up raising "AttributeError"

Traceback:
`Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\Test-u7DUJAa6\lib\site-packages\discord\commands\core.py", line 127, in wrapped
    ret = await coro(arg)
  File "C:\Users\HP\.virtualenvs\Test-u7DUJAa6\lib\site-packages\discord\commands\core.py", line 904, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "D:\Coding\Test\cogs\cog.py", line 12, in start_election
    await channel.send("View", view=MyView())
  File "C:\Users\HP\.virtualenvs\Test-u7DUJAa6\lib\site-packages\discord\abc.py", line 1465, in send
    components = view.to_components()
  File "C:\Users\HP\.virtualenvs\Test-u7DUJAa6\lib\site-packages\discord\ui\view.py", line 217, in to_components
AttributeError: 'MyView' object has no attribute 'children'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\.virtualenvs\Test-u7DUJAa6\lib\site-packages\discord\bot.py", line 997, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "C:\Users\HP\.virtualenvs\Test-u7DUJAa6\lib\site-packages\discord\commands\core.py", line 359, in invoke
    await injected(ctx)
  File "C:\Users\HP\.virtualenvs\Test-u7DUJAa6\lib\site-packages\discord\commands\core.py", line 135, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: 'MyView' object has no attribute `'children'

### Intents

discord.Intents.all() (I know I should not be passing this, but it was just for testing)

### System Information

- Python v3.10.7-final
- py-cord v2.1.0-final
- aiohttp v3.8.1

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by NeloBlivion** [comment]
Not a lib issue, you need to `super().__init__()` since you overrode the default `__init__` function
