### ISSUE TITLE
SlashCommandGroup does not register correctly

### ISSUE THREAD

**Issue by M1N0RM1N3R** [Pycord-Development/pycord#1649]
### Summary

SlashCommandGroups don't appear to be registering properly--when I start up my bot, the commands in SlashCommandGroups appear broken, whereas commands not in a group work fine.

### Reproduction Steps

1. Create a SlashCommandGroup via `foo_cmd = discord.SlashCommandGroup('foo')`
2. Add commands to it via `@foo_cmd.command()`
3. Add the group to the bot via `bot.add_application_command(foo_cmd)`
4. Add a regular command via `@bot.slash_command()` to compare and contrast for good measure

### Minimal Reproducible Code

```python
@bot.slash_command()
async def ping(
    ctx: discord.ApplicationContext,
):
    await ctx.send_response(f"🏓 Pong! Latency: {bot.latency} secs. Active since <t:{int(login_time)}>. Version: {VERSION}", ephemeral=True)

profile_cmd = discord.SlashCommandGroup('profile')


@profile_cmd.command(name='create')
async def profile_create(
    ctx: discord.ApplicationContext,
    name: str
):
    profile = Profile(ctx.author.id, name)
    db.add(profile)
    await ctx.send_response('✅ Profile created:', embed=profile.profile_embed(), ephemeral=True)


@profile_cmd.command(name='get')
async def profile_get(
    ctx: discord.ApplicationContext,
    user: discord.Option(
        discord.Member, description='Select another user to look up their profile, or leave alone to get your own. (#bars)', default=None)
):
    user: discord.Member = user or ctx.author

    profile: Profile = db.get(lambda x: x.discord_id == user.id)
    if profile:
        await ctx.send_response(embed=profile.profile_embed(), ephemeral=True)
    else:
        await ctx.send_response('❌ Profile not found.', ephemeral=True)

bot.add_application_command(profile_cmd)
```

### Expected Results

Command shows correct args in Discord client, command runs as programmed

### Actual Results

Commands created via `@bot.slash_command()` such as the /ping command in the MPC example function as expected.
The commands in the SlashCommandGroup appear blank, with only the name. No arguments appear at all.
When attempting to run one of the commands in the group, Discord shows a "The application did not respond" error and the terminal shows the following traceback.
When I change the `@profile_cmd.command()` to `@bot.slash_command()`, the command works perfectly.
```
Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 127, in wrapped
    ret = await coro(arg)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 1201, in _invoke
    await command.invoke(ctx)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 356, in invoke
    await self.prepare(ctx)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 278, in prepare
    if not await self.can_run(ctx):
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 373, in can_run
    local_check = cog._get_overridden_method(cog.cog_check)
AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/bot.py", line 1009, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 359, in invoke
    await injected(ctx)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 135, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/bot.py", line 1058, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/bot.py", line 756, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/bot.py", line 1013, in invoke_application_command
    await ctx.command.dispatch_error(ctx, exc)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 401, in dispatch_error
    local = cog.__class__._get_overridden_method(cog.cog_command_error)
AttributeError: type object '_MissingSentinel' has no attribute '_get_overridden_method'
Ignoring exception in command profile create:
Traceback (most recent call last):
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 127, in wrapped
    ret = await coro(arg)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 1201, in _invoke
    await command.invoke(ctx)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 356, in invoke
    await self.prepare(ctx)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 278, in prepare
    if not await self.can_run(ctx):
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 373, in can_run
    local_check = cog._get_overridden_method(cog.cog_check)
AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/bot.py", line 1009, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 359, in invoke
    await injected(ctx)
  File "/home/<username>/.local/lib/python3.10/site-packages/discord/commands/core.py", line 135, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'
```

### Intents

None at the moment

### System Information

- Python v3.10.6-final
- py-cord v2.1.3-final
- aiohttp v3.8.3
- system info: Linux 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I believe this has worked properly in the past when I was running on Windows. It could just be me, but it suddenly stopped working after I switched over to Ubuntu 22.04 last weekend.

**Comment by JustaSqu1d** [comment]
Does the workaround of using `bot.create_group` not solve this issue?

**Comment by M1N0RM1N3R** [comment]
> Does the workaround of using `bot.create_group` not solve this issue?

Hmm, lemme try that...

**Comment by voidus** [comment]
As a workaround, you can add `my_command.cog = None` after the command creation like so:

```
g = bot.create_group("g")

@b.command()
async def foo(ctx):
  ctx.respond("heya")
  
foo.cog = None
```

No idea if this has any side effects though.

**Comment by JustaSqu1d** [comment]
#1662
