### ISSUE TITLE
Incompatible with Python 3.11

### ISSUE THREAD

**Issue by ImNarukami** [Pycord-Development/pycord#1752]
### Summary

Error with py-cord with Python 3.11

### Reproduction Steps

Steps:
- Start a bot on Python 3.11 with py-cord

### Minimal Reproducible Code

```python
from discord.ext import commands
```

### Expected Results

My bot to run as it should? Not sure what else to put here. The code is stable except for this issue.

### Actual Results

Traceback (most recent call last):
  File "c:\Users\User\Desktop\Kaia-main\Minimum.py", line 1, in <module>
    from discord.ext import commands
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\__init__.py", line 18, in <module>
    from .flags import *
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\flags.py", line 57, in <module>
    @dataclass
  ^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1221, in dataclass
    return wrap(cls)
      ^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usere\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory

### Intents

discord.Intents.all() 

### System Information

- Python v3.11.0-final
- py-cord v2.2.2-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19045

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Wasn't an issue before python 3.11

I know that I could easily just go back but I figured you'd want to know about this issue.

**Comment by plun1331** [comment]
This is fixed on the master branch already, you can install it with `pip install git+https://github.com/pycord-development/pycord`
