### ISSUE TITLE
ValueError when importing commands from discord.ext

### ISSUE THREAD

**Issue by montw-dev** [Pycord-Development/pycord#1778]
### Summary

When importing commands from discord.ext I get a ValueError

### Reproduction Steps

1. Run `from discord.ext import commands`
2. You will get a ValueError

### Minimal Reproducible Code

```python
from discord.ext import commands
```

### Expected Results

commands should be successfully imported from discord.ext

### Actual Results

I got a long stack trace:

`Traceback (most recent call last):
  File "/Users/montw/dev/gen2/src/bot/ext/core.py", line 2, in <module>
    from discord.ext import commands
  File "/Users/montw/dev/gen2/.venv/lib/python3.11/site-packages/discord/ext/commands/__init__.py", line 18, in <module>
    from .flags import *
  File "/Users/montw/dev/gen2/.venv/lib/python3.11/site-packages/discord/ext/commands/flags.py", line 71, in <module>
    @dataclass
     ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory`

### Intents

discord.Intents.default()

### System Information

- Python v3.11.0-final
- py-cord v2.1.3-final
- aiohttp v3.8.3
- system info: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I am running Python 3.11 on macOS Monterey

**Comment by qwixck** [comment]
install pycord from master branch, it's already fixed there

**Comment by montw-dev** [comment]
Ok
