### ISSUE TITLE
sync_commands Error

### ISSUE THREAD

**Issue by Wolfy024** [Pycord-Development/pycord#1926]
### Summary

Whenever we use sync_commands(), it raises "Application command names must be unique" Error.

### Reproduction Steps

Sync Commands

### Minimal Reproducible Code

```python
@bot.slash_command(name="load",guild_ids=GUILD)                    
async def load(ctx: discord.Interaction,extension:str):    
    if(ctx.author.id in ADMINS):
        try:
            print(extension)
            bot.load_extension(f'{extension}')
            await bot.sync_commands()
            await ctx.response.send_message("Cog loaded.",ephemeral=True)
        except Exception as E:
            await ctx.response.send_message(E,ephemeral=True)
            raise E

..................................


class LANGUAGE_SELECTION(discord.ext.commands.Cog):
    def __init__(self,bot):
        self.bot=bot
    
    def auto():
        return LANGUAGES
    
    @bot.slash_command(guild=config.GUILD, description="Set your Translator Language.")   #Come on, you know what this is.
    async def set_language(ctx: discord.Interaction,language: Option(input_type=str,description="Select a Language.",autocomplete=auto())):
        print(language)
        
  

def setup(bot):             
    bot.add_cog(LANGUAGE_SELECTION(bot))
```

### Expected Results

For it to work.

### Actual Results

Ignoring exception in command load_all:
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 124, in wrapped
    ret = await coro(arg)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\commands\core.py", line 980, in _invoke
    await self.callback(ctx, **kwargs)
  File "e:\Python Projects\Translator\Core\Cog_gathering.py", line 58, in load_all
    raise E
  File "e:\Python Projects\Translator\Core\Cog_gathering.py", line 52, in load_all
    await bot.sync_commands()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\bot.py", line 719, in sync_commands
    registered_commands = await self.register_commands(
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\bot.py", line 599, in register_commands
    registered = await register("bulk", data, _log=False)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 366, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In 1: Application command names must be unique

### Intents

all

### System Information

- Python v3.10.5-final
- py-cord v2.3.2-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Wolfy024** [comment]
i saw a bug like this from september, 2022 but it was too old so...

**Comment by Wolfy024** [comment]
i updated to 2.4.0 and still same issue.
