### ISSUE TITLE
ForumChannel doesn't properly offer available_tags if fetched from discord.Message or Client.fetch_channel

### ISSUE THREAD

**Issue by sakurazaki** [Pycord-Development/pycord#1930]
### Summary

Trying to access the attribute raises an error

### Reproduction Steps

1. Create a minimal Bot to read messages from chat
2. Create a Forum channel
3. Create a thread
4. Type anything in the thread and have the bot read the message in on_message event
5. Try accessing availabe_tags through message.channel.parent.available_tags (parent is available through discord.Thread)

### Minimal Reproducible Code

```python
import discord

class Bot(discord.AutoShardedBot):
    async def on_message(self, message: discord.Message) -> None:
        print(message.channel.parent.available_tags)
```

### Expected Results

I expected to get the list of available tags in the ForumsChannel

### Actual Results

```
ERROR:discord:Bot handled an error on event: 
    ('on_message', <Message id=1076409045612769310 channel=<Thread parent=forumchannel locked=False archived=False>
    type=<MessageType.default: 0> author=<Member ...>> flags=<MessageFlags value=0>>) with error:
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\discord\client.py", line 377, in _run_event
    await coro(*args, **kwargs)
  File "~\bot.py", line 86, in on_message
    await self.handle_commands(message)
  File "~\forums.py", line 63, in update_tags
    tags = [tag for tag in context.channel.parent.available_tags if "new" in tag.name]
AttributeError: 'ForumChannel' object has no attribute 'available_tags
```

### Intents

discord.all

### System Information

- Python v3.10.1-final
- py-cord v2.4.None-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by sakurazaki** [comment]
My apologies, turns out there was versioning issue in my end and somehow while the version printing said py-cord v2.4 the version being executed was 2.2 and was raising the error above. This issue may be closed.
