### ISSUE TITLE
Using asyncio.TaskGroup() somehow breaks error handling

### ISSUE THREAD

**Issue by honzajavorek** [Pycord-Development/pycord#1986]
### Summary

Using `asyncio.TaskGroup()` inside the Discord client's framework causes issues with handling exceptions

### Reproduction Steps

1. Copy-paste the quickstart code from the PyCord docs.
2. Change it to this:

```python
import os
import discord
import logging

logging.basicConfig(level=logging.DEBUG)
logging.getLogger('discord').setLevel(logging.ERROR)

intents = discord.Intents.default()
intents.message_content = True

client = discord.Client(intents=intents)

@client.event
async def on_ready():
    logging.info(f'We have logged in as {client.user}')
    raise RuntimeError('Ouch!')

@client.event
async def on_error(event_name, *args, **kwargs):
    logging.info('Got an error! Re-raising')
    raise

def handler(loop, context):
    logging.info('Delegating to default exception handler')
    loop.default_exception_handler(context)
    logging.info('Shutting down!')
    loop.stop()

client.loop.set_exception_handler(handler)
client.run(os.environ['DISCORD_API_KEY'])
```

3. Run it. It should run and gracefully shut down, printing the exception along the way. **This is expected!** The program doesn't hang, it finishes and returns control over the terminal to the user. The log looks like this:

```shell
$ python specimen.py 
DEBUG:asyncio:Using selector: KqueueSelector
INFO:root:We have logged in as kuře#7420
INFO:root:Got an error! Re-raising
INFO:root:Delegating to default exception handler
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='pycord: on_ready' coro=<Client._run_event() done, defined at /Users/honza/Library/Caches/pypoetry/virtualenvs/juniorguru-Lgaxwd2n-py3.11/lib/python3.11/site-packages/discord/client.py:370> exception=RuntimeError('Ouch!')>
Traceback (most recent call last):
  File "/Users/honza/Library/Caches/pypoetry/virtualenvs/juniorguru-Lgaxwd2n-py3.11/lib/python3.11/site-packages/discord/client.py", line 383, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "/Users/honza/Library/Caches/pypoetry/virtualenvs/juniorguru-Lgaxwd2n-py3.11/lib/python3.11/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/Users/honza/Projects/juniorguru/specimen.py", line 24, in on_ready
    raise RuntimeError('Ouch!')
RuntimeError: Ouch!
INFO:root:Shutting down!
```

4. Edit the code as follows:

```diff
+ import asyncio

client = discord.Client(intents=intents)

+ async def something(n):
+     await asyncio.sleep(n)

@client.event
async def on_ready():
    logging.info(f'We have logged in as {client.user}')
+   async with asyncio.TaskGroup() as tasks:
+       tasks.create_task(something(1))
+       tasks.create_task(something(2))
+   logging.info('Tasks done!')
    raise RuntimeError('Ouch!')
```

5. Run it. It should run and hang. **This is not expected!** The log looks like this:

```shell
$ python specimen.py 
DEBUG:asyncio:Using selector: KqueueSelector
INFO:root:We have logged in as kuře#7420
INFO:root:Tasks done!
INFO:root:Got an error! Re-raising
```

6. Press <kbd>Ctrl+C</kbd> to interrupt the program. Only then you'll see the exception handled and the output flushed to the terminal:

```shell
$ python specimen.py 
DEBUG:asyncio:Using selector: KqueueSelector
INFO:root:We have logged in as kuře#7420
INFO:root:Tasks done!
INFO:root:Got an error! Re-raising
^C
INFO:root:Delegating to default exception handler
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='pycord: on_ready' coro=<Client._run_event() done, defined at /Users/honza/Library/Caches/pypoetry/virtualenvs/juniorguru-Lgaxwd2n-py3.11/lib/python3.11/site-packages/discord/client.py:370> exception=RuntimeError('Ouch!')>
Traceback (most recent call last):
  File "/Users/honza/Library/Caches/pypoetry/virtualenvs/juniorguru-Lgaxwd2n-py3.11/lib/python3.11/site-packages/discord/client.py", line 383, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "/Users/honza/Library/Caches/pypoetry/virtualenvs/juniorguru-Lgaxwd2n-py3.11/lib/python3.11/site-packages/discord/client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "/Users/honza/Projects/juniorguru/specimen.py", line 24, in on_ready
    raise RuntimeError('Ouch!')
RuntimeError: Ouch!
INFO:root:Shutting down!
```

### Minimal Reproducible Code

See above.

### Expected Results

I expect the code won't hang and the exception gets gracefully handled, similar to phase 3 of my step-by-step reproduction.

### Actual Results

The code hangs and the exception never makes it to the error handling mechanics after being re-raised from `on_error`. Re-raising like this is something that works without `asyncio.TaskGroup()` in the code and it is [a recommended approach in the documentation](https://docs.pycord.dev/en/master/api/events.html#discord.on_error):

<img width="792" alt="Screenshot 2023-03-28 at 10 23 46" src="https://user-images.githubusercontent.com/283441/228175334-24362bce-0176-4321-9f44-f8175ee91063.png">

### Intents

the default set

### System Information

```shell
$ python -m discord -v
- Python v3.11.2-final
- py-cord v2.4.None-final
- aiohttp v3.8.4
- system info: Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Originally I observed the same behavior when the exception actually originated from one of the tasks. I suspected that the `discord.Client()` code might have a `try/except` somewhere, which only counts with `Exception`. The `asyncio.TaskGroup()` raises `BaseExceptionGroup`, which wouldn't be handled in such case, as [the hierarchy looks like this](https://docs.python.org/3/library/exceptions.html#exception-hierarchy):

```
BaseException
 ├── BaseExceptionGroup
 ├── GeneratorExit
 ├── KeyboardInterrupt
 ├── SystemExit
 └── Exception
```

But my minimal example shows that it probably doesn't really matter where it originates from. My exception `RuntimeError('Ouch!')` is not related to the `asyncio.TaskGroup()` or its tasks. It seems the mere presence of the `asyncio.TaskGroup()` block is enough to cause the issue for any exception that follows.

----

It's possible that I'm using the `asyncio.TaskGroup()` wrong way. In that case I'm sorry for filing this, but I've re-read [the docs](https://docs.python.org/3/library/asyncio-task.html#task-groups) multiple times and I can't see what I'd be doing wrong. It's also fairly new. [I can see fixes](https://docs.python.org/3/whatsnew/changelog.html) in Python 3.11.0 release candidate 1, but that's already many versions and a year ago 🤔 I didn't look into Python's own bug tracker though.

**Comment by honzajavorek** [comment]
I consulted @messa and he found out that the issue is related how Python, or specifically cpython, works:

> In your case, you actually want to catch the "Task exception was never retrieved" exception with your loop exception handler, and it's exactly the same type of problem as with the destructor. The exception `{self.__class__.__name__} exception was never retrieved` even arises directly in `Future.__del__`.
>
> How does Python know that the exception was never retrieved? It knows because there's no chance anyone will pick up the exception anymore, since no one holds a reference to the task object. But when you put a `TaskGroup` into the code, the `TaskGroup` [holds a reference to the task object](https://github.com/python/cpython/blob/7703def37e4fa7d25c3d23756de8f527daa4e165/Lib/asyncio/taskgroups.py#L63), and the reference to the `TaskGroup` is probably somewhere in memory even after the entire `fail()` function has finished - I'm not sure where, the raised exception probably holds the scope of the function somehow. But when you put `del tasks` right after the async with block (at least in my example), the loop exception handler is called right away, so it behaves as you expect.

This solves it:

```diff
 @client.event
 async def on_ready():
     logging.info(f'We have logged in as {client.user}')
     async with asyncio.TaskGroup() as tasks:
         tasks.create_task(something(1))
         tasks.create_task(something(2))
+    del tasks
     logging.info('Tasks done!')
     raise RuntimeError('Ouch!')
```

Also using `asyncio.gather()` instead solves it. Not sure whether this is a bug or feature in Python, it's definitely some unexpected magic. And it's definitely not related to Pycord.
