### ISSUE TITLE
copy.copy() + discord.Client.start() exception

### ISSUE THREAD

**Issue by davidhozic** [Pycord-Development/pycord#2051]
### Summary

When copying the newly created ``discord.Client`` with ``copy.copy()`` function an exception occurs after ``Client.start()``.

### Reproduction Steps

See the code below.

### Minimal Reproducible Code

```python
import discord
import copy
import asyncio


TOKEN = ""
loop = asyncio.get_event_loop()

client = discord.Client(loop=loop)
client = copy.copy(client)  # If commented out, works


async def main():
    asyncio.create_task(client.start(TOKEN))
    await client.wait_for("ready", timeout=5)

    channel: discord.VoiceChannel = client.get_channel(1104446207931203665)
    await channel.connect()
    ...


loop.run_until_complete(main())
```

### Expected Results

Not to raise an exception inside the library.

### Actual Results

Raises exeption somewhere internal of the library.

The above example code yields the following:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\David\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>    
    cli.main()
  File "c:\Users\David\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\David\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\David\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\David\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code    
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\David\.vscode\extensions\ms-python.python-2023.6.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\development\GIT\discord-advertisement-framework\test.py", line 22, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\development\GIT\discord-advertisement-framework\test.py", line 18, in main
    await channel.connect()
  File "C:\development\GIT\discord-advertisement-framework\src\_discord\abc.py", line 1942, in connect
    await voice.connect(timeout=timeout, reconnect=reconnect)
  File "C:\development\GIT\discord-advertisement-framework\src\_discord\voice_client.py", line 393, in connect
    await self.voice_connect()
  File "C:\development\GIT\discord-advertisement-framework\src\_discord\voice_client.py", line 346, in voice_connect
    await self.channel.guild.change_voice_state(channel=self.channel)
  File "C:\development\GIT\discord-advertisement-framework\src\_discord\guild.py", line 3429, in change_voice_state
    await ws.voice_state(self.id, channel_id, self_mute, self_deaf)
AttributeError: 'NoneType' object has no attribute 'voice_state'

### Intents

No intents were passed

### System Information

- Python v3.8.10-final
- py-cord v2.4.1-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
Why are you copying the client?

**Comment by davidhozic** [comment]
> Why are you copying the client?

I have a project in which I have object serialization. One of the objects contains ``discord.Client`` as an attribute which is not being serialized but instead recreated separately after deserialization. ``discord.Client`` is not the only thing that works this way, thus I have a ``dict`` mapping which maps a class to a ``dict`` of attributes which values are attribute defaults to use (one of these is a ``discord.Client`` instance).  Since I want these class values to be reusable, I am copying them otherwise they would get modified inside the dictionary


```py
client.ACCOUNT: {
        "attrs": client.ACCOUNT.__slots__,
        "attrs_restore": {
            "tasks": [],
            "_client": lambda account: discord.Client(intents=account.intents, connector=None),
            "_update_sem": asyncio.Semaphore(1),
            "_running": False
        },
    },
```

**Comment by davidhozic** [comment]
As a temp solution I added
```py
  if not isinstance(v, discord.Client):
```
, but the deserialization is a bit slower this way.

**Comment by Pixel2075** [comment]
The `discord.Client` class is a client for the Discord API, and copying it may lead to unexpected behavior and issues, as it represents a live connection to the Discord servers. It is generally recommended to recreate the client object instead of copying it when needed.

If you need to persist the state of the `discord.Client` object for serialization purposes, you should consider storing the necessary information required to recreate the client object, such as the token, relevant IDs, and any other configuration or state information. Then, upon deserialization, you can use that information to recreate the discord.Client instance.

**Comment by Lulalaby** [comment]
Thanks @Pixel2075 for helping out
