### ISSUE TITLE
ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory

### ISSUE THREAD

**Issue by DARSHTRON** [Pycord-Development/pycord#2110]
### Summary

ValueError after updating to master

### Reproduction Steps

i just updated to `py-cord-2.4.1.dev119+ge5aafe45` because global_names update and every single cog got the error
`ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory`
this error starts especially from the `from discord import option` decorator and `from discord.ext import commands` which's similar to issue #1778 

### Minimal Reproducible Code

```python
# pip install -U git+https://github.com/Pycord-Development/pycord | # py-cord-2.4.1.dev119+ge5aafe45
import discord
from discord import option # COGS ONLY ISSUE
from discord.ext import command # WINDOWS ONLY AFTER TEST

...
```

### Expected Results

everything works fine as intended to be

### Actual Results

ValueError appears on cogs

### Intents

discord.Intents.all()

### Windows machine
- Python v3.11.2-final
- py-cord v2.4.1-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19044
### Linux machine (Manjaro)
smth.. `
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/darsh/.local/lib/python3.10/site-packages/discord/__main__.py", line 33, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

this is a windows Traceback for `discord.ext.commands`
```py
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import discord
>>> from discord.ext import commands
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\__init__.py", line 18, in <module>
    from .flags import *
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\flags.py", line 57, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1220, in dataclass
           ^^^^^^^^^
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory
>>>
```
NOTE: this error above only appears to my windows machine, Manjaro Linux have no issue to import it

and the issue on the `discord.option` seems to be appears on cogs only and i didn't have test that on liunx due lack of time

here is a Traceback for the `discord.option` issue with cogs

```py
PS D:\discord_tests> python .\main.py
Traceback (most recent call last):
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\cog.py", line 777, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\discord_tests\cog.py", line 5, in <module>
    class test(discord.Cog):
  File "D:\discord_tests\cog.py", line 10, in test
    @option(name="text", description='test option',)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\commands\options.py", line 415, in decorator
    func.__annotations__[name] = Option(type, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\commands\options.py", line 214, in __init__
    from ..ext.commands import Converter
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\__init__.py", line 18, in <module>
    from .flags import *
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ext\commands\flags.py", line 57, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\discord_tests\main.py", line 6, in <module>
    bot.load_extension('cog')
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\cog.py", line 913, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\DARSH\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\cog.py", line 780, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'cog' raised an error: ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory
PS D:\discord_tests>
```
NOTE: everything works just fine with older versions (i didn't freezed that version which was also master) 
the common thing is the error `ValueError: mutable default <class 'discord.utils._MissingSentinel'> for field name is not allowed: use default_factory` between the two imports

**Comment by T0bycat** [comment]
May I ask what version you've switched to?  I'd like to start working on my bot but this error is a big hitch in my plans... Thanks!

**Comment by DARSHTRON** [comment]
> ~May I ask what version you've switched to? I'd like to start working on my bot but this error is a big hitch in my plans... Thanks!~
> 
> Edit: The error was fixed by completely re-initializing my venv, and only installing py-cord. i think there was conflict with the uninstalled discord.py and hikari.

issue still with me with master, and i planning for a PR but have no idea if this issue is effected by files that i edited so i'll wait, by the way the i mentioned the master branch id
