### ISSUE TITLE
AttributeError: 'Interaction' object has no attribute 'entitlements'

### ISSUE THREAD

**Issue by tibue99** [Pycord-Development/pycord#2344]
### Summary

The newest verision (2.4.1.dev241+g9683629e) crashes when executing slash commands

### Reproduction Steps

Start the bot code below and run the `hello` command

### Minimal Reproducible Code

```python
import discord

bot = discord.Bot()

@bot.slash_command()
async def hello(ctx):
    await ctx.respond("Hello!")

bot.run("")
```

### Expected Results

Bot responds with `Hello!`

### Actual Results

```
Traceback (most recent call last):
  File "C:\Users\Timo\Desktop\pythonProject\main.py", line 11, in <module>
    bot.run("...")
  File "C:\Users\Timo\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 766, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Timo\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 745, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Timo\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 709, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Timo\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 601, in connect
    await self.ws.poll_event()
  File "C:\Users\Timo\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\gateway.py", line 604, in poll_event
    await self.received_message(msg.data)
  File "C:\Users\Timo\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\gateway.py", line 554, in received_message
    func(data)
  File "C:\Users\Timo\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\state.py", line 816, in parse_interaction_create
    interaction = Interaction(data=data, state=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Timo\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\interactions.py", line 170, in __init__
    self._from_data(data)
  File "C:\Users\Timo\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\interactions.py", line 187, in _from_data
    self.entitlements: list[Entitlement] = [
    ^^^^^^^^^^^^^^^^^
AttributeError: 'Interaction' object has no attribute 'entitlements'
```

### Intents

-

### System Information

- Python v3.10.9-final
- py-cord v2.4.1-final
- aiohttp v3.9.1
- system info: Windows 10 10.0.22631

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by JustaSqu1d** [comment]
Cannot reproduce on 3.11.7, but reproducible on 3.12.1
