### ISSUE TITLE
'Bot' object has no attribute 'logout'

### ISSUE THREAD

**Issue by DanialHMD** [Pycord-Development/pycord#2372]
### Summary

Error on shutdown command.

### Reproduction Steps

basically the code is like this:
```python
intents = discord.Intents.default()
intents.members = True
intents.message_content = True

bot = commands.Bot(
    command_prefix=commands.when_mentioned_or("?"),
    description=description,
    intents=intents,
)

@bot.command()
@commands.is_owner()
async def shutdown(ctx):
    await ctx.bot.logout()
```
There is more commands and classes defined in the main code, but the problem I see is in this part.
I ran the code, give command in text channel, and error raised in terminal.

### Expected Results

What is expected is that with this command the bot shuts down and stops working.

### Actual Results

```terminal
Ignoring exception in command shutdown:
Traceback (most recent call last):
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\core.py", line 178, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\Codes\Python\Discord\main.py", line 162, in shutdown
    await ctx.bot.logout()
          ^^^^^^^^^^^^^^
AttributeError: 'Bot' object has no attribute 'logout'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\bot.py", line 347, in invoke  
    await ctx.command.invoke(ctx)
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\core.py", line 950, in invoke 
    await injected(*ctx.args, **ctx.kwargs)
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\core.py", line 187, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Bot' object has no attribute 'logout'
Ignoring exception in command join:
Traceback (most recent call last):
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\bot.py", line 347, in invoke
    await ctx.command.invoke(ctx)
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\core.py", line 942, in invoke
    await self.prepare(ctx)
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\core.py", line 872, in prepare
    await self._parse_arguments(ctx)
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\core.py", line 783, in _parse_arguments
    kwargs[name] = await self.transform(ctx, param)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\core.py", line 601, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: channel is a required argument that is missing.
Ignoring exception in command shutdown:
Traceback (most recent call last):
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\core.py", line 178, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\Codes\Python\Discord\main.py", line 162, in shutdown
    await ctx.bot.logout()
          ^^^^^^^^^^^^^^
AttributeError: 'Bot' object has no attribute 'logout'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\bot.py", line 347, in invoke
    await ctx.command.invoke(ctx)
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\core.py", line 950, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "f:\Codes\Python\disbot\Lib\site-packages\discord\ext\commands\core.py", line 187, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Bot' object has no attribute 'logout'
```

### Intents

MESSAGE CONTENT INTENT, SERVER MEMBERS INTENT, PRESENCE INTENT

### System Information

```
- Python v3.11.7-final
- py-cord v2.4.1-final
- aiohttp v3.8.6
- system info: Windows 10 10.0.19045
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
Your error is correct, `Bot` does not (and should not) have a `logout` attribute.

**Comment by Revnoplex** [comment]
I believe you are looking for `ctx.bot.close()`
