### ISSUE TITLE
Cannot use Union type alias for command `ctx` parameter

### ISSUE THREAD

**Issue by Paillat-dev** [Pycord-Development/pycord#2610]
### Summary

One cannot use a union type alias in when typing a command's ctx parameter.

### Reproduction Steps

Run the below code.

### Minimal Reproducible Code

```python
import discord
import os

from dotenv import load_dotenv
import logging
from discord.ext import commands, bridge

logging.basicConfig(level=logging.INFO)

load_dotenv()
TOKEN = os.getenv("TOKEN")

bot = bridge.Bot(intents=discord.Intents.all())


class MyApplicationContext(bridge.BridgeApplicationContext):
    pass


class MyExtContext(bridge.BridgeExtContext):
    pass


AnyContext = MyExtContext | MyApplicationContext


class MyCog(commands.Cog):
    def __init__(self, bot: bridge.Bot):
        self.bot = bot

    @bridge.bridge_command()
    async def ping(self, ctx: AnyContext):
        await ctx.respond("Pong!")


bot.add_cog(MyCog(bot))
bot.run(TOKEN)
```

### Expected Results

The code running like normal.

### Actual Results

The code crashing and the bot never starting with the following traceback:
```
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
Traceback (most recent call last):
  File "C:\Users\Jérémie\Documents\GitHub\pycord-sandbox\aaa2.py", line 27, in <module>
    class MyCog(commands.Cog):
  File "C:\Users\Jérémie\Documents\GitHub\pycord-sandbox\aaa2.py", line 31, in MyCog
    @bridge.bridge_command()
     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jérémie\Documents\GitHub\pycord-sandbox\.venv\Lib\site-packages\discord\ext\bridge\core.py", line 448, in decorator
    return BridgeCommand(callback, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jérémie\Documents\GitHub\pycord-sandbox\.venv\Lib\site-packages\discord\ext\bridge\core.py", line 191, in __init__
    ) or BridgeSlashCommand(callback, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jérémie\Documents\GitHub\pycord-sandbox\.venv\Lib\site-packages\discord\ext\bridge\core.py", line 84, in __init__
    super().__init__(func, **kwargs)
  File "C:\Users\Jérémie\Documents\GitHub\pycord-sandbox\.venv\Lib\site-packages\discord\commands\core.py", line 762, in __init__
    self._validate_parameters()
  File "C:\Users\Jérémie\Documents\GitHub\pycord-sandbox\.venv\Lib\site-packages\discord\commands\core.py", line 780, in _validate_parameters
    self.options = self._parse_options(params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jérémie\Documents\GitHub\pycord-sandbox\.venv\Lib\site-packages\discord\commands\core.py", line 828, in _parse_options
    option = Option(option.__args__)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jérémie\Documents\GitHub\pycord-sandbox\.venv\Lib\site-packages\discord\commands\options.py", line 245, in __init__
    raise exc
  File "C:\Users\Jérémie\Documents\GitHub\pycord-sandbox\.venv\Lib\site-packages\discord\commands\options.py", line 240, in __init__
    self.input_type = SlashCommandOptionType.from_datatype(input_type)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jérémie\Documents\GitHub\pycord-sandbox\.venv\Lib\site-packages\discord\enums.py", line 801, in from_datatype
    raise TypeError("Invalid usage of typing.Union")
TypeError: Invalid usage of typing.Union
```

### Intents

discord.Intents.all()

### System Information

- Python v3.11.9-final
- py-cord vNone.1.None-final (latest from master)
- aiohttp v3.10.10
- system info: Windows 10 10.0.22635

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The same error does happen with `discord.slash_command` and `commands.command` however I choose the bridge example as there would actually be a reason there for using an union type for ctx.

**Comment by Paillat-dev** [comment]
Actually my bad this is a duplicate of
- #2378
