### ISSUE TITLE
Support GUILD_MEDIA channel type

### ISSUE THREAD

**Issue by tibue99** [Pycord-Development/pycord#2637]
### Summary

Messages in GUILD_MEDIA channels can lead to errors in current bots if they are not implemented.

### What is the feature request for?

The core library

### The Problem

When trying to fetch a media channel, an `InvalidData` error is thrown.
- Reference: https://discord.com/developers/docs/change-log#new-guildmedia-channel-type

### The Ideal Solution

Add `GUILD_MEDIA` as a channel type

**Comment by NeloBlivion** [comment]
Media channels are hard to test because of their beta/exclusivity status, but for the most part they should operate the same as ForumChannel - do you have any examples/tracebacks we can look at? Or is it just the fact we never added the `GUILD_MEDIA` type (i.e. if you add `media` to `enums.py -> ChannelType`, does that fix your issues?)

**Comment by tibue99** [comment]
It's hard to test for me, but here is my traceback 
```
Traceback (most recent call last):
  File "/home/container/cogs/level_system.py", line 254, in on_message
    category_id = msg.channel.category_id
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/threads.py", line 377, in category_id
    raise ClientException("Parent channel not found")
discord.errors.ClientException: Parent channel not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.11/site-packages/discord/client.py", line 442, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/cogs/level_system.py", line 257, in on_message
    parent_channel = await get_or_fetch(
                     ^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/utils.py", line 624, in get_or_fetch
    getter = await getattr(obj, f"fetch_{attr}")(id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/client.py", line 1878, in fetch_channel
    raise InvalidData(
discord.errors.InvalidData: Unknown channel type 16 for channel ID 1299532652516216956.
```

**Comment by Lulalaby** [comment]
Yeah that's the problem, I'm gonna fix it on master, please test it.
Guild media channels have some extra properties but that shouldn't pose a problem.

**Comment by tibue99** [comment]
To reproduce this, a media channel can ID be put into `utils.get_or_fetch`
