### ISSUE TITLE
@commands.Cog.listener() raises errors

### ISSUE THREAD

**Issue by KosmicAnomaly** [Pycord-Development/pycord#290]
### Summary

We currently are unable to setup listeners in Cogs

### Reproduction Steps

Try to setup a listener in a Cog

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

class Palindrome(commands.Cog):
    def __init__(self, bot):
        self.BlackHole = bot

    @commands.Cog.listener()
    async def on_message(self, message: discord.Message):
        print(message.content)

def setup(bot):
    bot.add_cog(Palindrome(bot))
```

### Expected Results

Have a functioning listener

### Actual Results

Traceback (most recent call last):
  File "C:\Users\foobar\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 668, in _load_from_module_spec
    setup(self)
  File "C:\Users\foobar\Desktop\Code\DiscordBots\BlackHole\Modules\Fun\Palindrome.py", line 36, in setup
    bot.add_cog(Palindrome(bot))
  File "C:\Users\foobar\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 550, in add_cog
    cog = cog._inject(self)
  File "C:\Users\foobar\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 474, in _inject
    bot.add_listener(getattr(self, method_name), name)
AttributeError: 'Bot' object has no attribute 'add_listener'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\foobar\Desktop\Code\DiscordBots\BlackHole\Bot.py", line 89, in <module>
    BlackHole.load_extension(fullpath[:-3])
  File "C:\Users\foobar\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 728, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\foobar\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 671, in _load_from_module_spec
    self._remove_module_references(lib.__name__)
  File "C:\Users\foobar\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\cog.py", line 617, in _remove_module_references
    for cmd in self.all_commands.copy().values():
AttributeError: 'Bot' object has no attribute 'all_commands'

### Intents

discord.Intents.all()

### System Information

- Python v3.9.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4089+g017deaeb
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by TheGamerX20** [comment]
> Can you try with discord.Cog? Also, are you using commands.Bot or discord.Bot?

Seems like this only happens when using discord.Bot, as it does not implement add_listener.
commands.Bot however does implement add_listener and it works without issues.

should they be implemented into discord.Bot?
