### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by popop098** [Pycord-Development/pycord#365]
### Summary

TypeError when using interaction

### Reproduction Steps

when using interaction with wait_for

### Minimal Reproducible Code

```python
@commands.command(name="test")
    async def test(self,ctx):
        msg = await ctx.reply("test",
                              components=[
                                  Select(placeholder="option",
                                         options=[
                                             SelectOption(label="No LV",
                                                          description="No LV.",
                                                          value="-HNoLv", emoji="🏆"),
                                             SelectOption(label="welcome", description="welcome.",
                                                          value="wlc", emoji="👋")
                                         ]),

                              ],
                              )

        def check(res):
            return ctx.author == res.user and res.channel == ctx.channel

        try:
            res = await self.bot.wait_for("select_option", check=check, timeout=60)
            user = res.values[0]
            await ctx.send(user)
        except asyncio.TimeoutError:
            await msg.edit(embed=discord.Embed(
                title="TimeOut."
            ))
```
```


### Expected Results

get interaction values

### Actual Results

```py
Ignoring exception in on_socket_response
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\harinbot\venv\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\harinbot\venv\lib\site-packages\pycord_components\client.py", line 46, in on_socket_response
    interaction = self._get_interaction(res)
  File "C:\Users\Administrator\Desktop\harinbot\venv\lib\site-packages\pycord_components\client.py", line 70, in _get_interaction
    ctx = Interaction(
  File "C:\Users\Administrator\Desktop\harinbot\venv\lib\site-packages\pycord_components\interaction.py", line 66, in __init__
    self.message: Union[ComponentMessage, dict] = ComponentMessage(
  File "C:\Users\Administrator\Desktop\harinbot\venv\lib\site-packages\pycord_components\dpy_overrides.py", line 26, in __init__
    super().__init__(state=state, channel=channel, data=data)
  File "C:\Users\Administrator\Desktop\harinbot\venv\lib\site-packages\discord\message.py", line 570, in __init__
    self.reference = ref = MessageReference.with_state(state, ref)
  File "C:\Users\Administrator\Desktop\harinbot\venv\lib\site-packages\discord\message.py", line 342, in with_state
    self.message_id = utils._get_as_snowflake(data, 'message_id')
  File "C:\Users\Administrator\Desktop\harinbot\venv\lib\site-packages\discord\utils.py", line 303, in _get_as_snowflake
    value = data[key]
TypeError: string indices must be integers
```

### Intents

discord.Intents.all()

### System Information

```py
- Python v3.8.9-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.17763
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment]
This cant be discord.py v1.7.3, are you using a 3rd party library?

**Comment by popop098** [comment]
yes, I'm using [Pycord-Components](https://github.com/Leek5/pycord-components)

**Comment by zeffo** [comment]
You should make an issue in that repo then, this issue isn't really related to pycord
