### ISSUE TITLE
BadArgument error without any explanation in cogs with AutoComplete

### ISSUE THREAD

**Issue by AwesomeSam9523** [Pycord-Development/pycord#393]
### Summary

BadArgument error without any explanation in cogs with AutoComplete

### Reproduction Steps

My Command:
```py
    @slash_command(usage="[@user/kirkaID] [set]", brief="View/Set tracker to track your progress in game by comparing your old stats with new one.", guild_ids=[868890520468983819])
    async def tracker(self, ctx: Context,
                      action: Option(str, "ABC", autocomplete=autoCompleteTracker),
                      kirka_id: Option(str, "ABC", autocomplete=autoCompleteTracker),
                      hidden: Option(str, description="ABC", required=False, choices=["Yes"])
                      ):
```
My AutoComplete:
```py
async def autoCompleteTracker(ctx: discord.AutocompleteContext, value=None):
    user = ctx.interaction.user.id
    d = bot.links.get(str(user))
    print(d)
    opt = ctx.focused.name
    if opt == "action":
        if d is None:
            treturn = ["Set"]
        all_acc = d["all"]
        left, set = getCachedTracker(bot, user, all_acc)
        if len(left) == 0:
            treturn = ["Update"]
        else:
            treturn = ["Set", "Update"]
    else:
        treturn =  [f"#{x}" for x in d["all"]]
    return treturn
```

### Minimal Reproducible Code

```python
`/tracker action: Update kirka_id: #1AI5EU hidden: Yes`
```

### Expected Results

Command should run or should tell what is the BadArgument

### Actual Results

Error:
```py
Ignoring exception in command <discord.commands.SlashCommand name=tracker>:
Traceback (most recent call last):
  File "/home/samaksh/PycharmProjects/beastlearnpy/venv/lib/python3.8/site-packages/discord/commands/commands.py", line 84, in wrapped
    ret = await coro(arg)
  File "/home/samaksh/PycharmProjects/beastlearnpy/venv/lib/python3.8/site-packages/discord/commands/commands.py", line 526, in _invoke
    await self.callback(self.cog, ctx, **kwargs)
  File "/home/samaksh/PycharmProjects/kirkabot/cogs/profile.py", line 818, in tracker
    raise discord.ext.commands.BadArgument
discord.ext.commands.errors.BadArgument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/samaksh/PycharmProjects/beastlearnpy/venv/lib/python3.8/site-packages/discord/bot.py", line 384, in process_application_commands
    await ctx.command.invoke(ctx)
  File "/home/samaksh/PycharmProjects/beastlearnpy/venv/lib/python3.8/site-packages/discord/commands/commands.py", line 133, in invoke
    await injected(ctx)
  File "/home/samaksh/PycharmProjects/beastlearnpy/venv/lib/python3.8/site-packages/discord/commands/commands.py", line 90, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: BadArgument: 
```

### Intents

intents = discord.Intents(             guild_reactions=True,             guild_messages=True,             guilds=True,             dm_messages=True,             members=True         )

### System Information

```
- Python v3.8.12-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4321+g8948a52
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-89-generic #100~18.04.1-Ubuntu SMP Wed Sep 29 10:59:04 UTC 2021
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by nerdguyahmad** [comment]
You are manually raising that error without any message in your application command's callback is raising that error (See line 818 in cogs/profile.py)
