### ISSUE TITLE
Can not register non-english slash command

### ISSUE THREAD

**Issue by penggin** [Pycord-Development/pycord#512]
### Summary

when slash command's name is non english, command cannot not register.

### Reproduction Steps

1. make a slash command has non-english name
2. run the bot process
3. it makes error!

### Minimal Reproducible Code

```python
@slash_command(name="테스트")
    async def test(self, ctx: ApplicationContext):
        pass
```

### Expected Results

The command should register.

like this
![image](https://user-images.githubusercontent.com/77449586/143613131-dc1145b6-29fb-4356-8af1-d7729419b27c.png)

### Actual Results

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 548, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "d:\GitHub\user\cmds\music\__init__.py", line 1, in <module>
    from .music import Music
  File "d:\GitHub\user\cmds\music\music.py", line 31, in <module>
    class Music(commands.Cog):
  File "d:\GitHub\user\cmds\music\music.py", line 70, in Music
    async def test(
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\commands.py", line 1110, in decorator
    return cls(func, **attrs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\commands.py", line 376, in __init__
    validate_chat_input_name(name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\commands.py", line 1133, in validate_chat_input_name
    raise ValidationError("Name of a chat input command must be lowercase.")
discord.errors.ValidationError: Name of a chat input command must be lowercase.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 173, in wrapped
    ret = await coro(*args, **kwargs)
  File "d:\GitHub\user\main.py", line 65, in bot_wakeup
    raise e
  File "d:\GitHub\user\main.py", line 62, in bot_wakeup
    bot.load_extension(extension)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 620, in load_extension
    self._load_from_module_spec(spec, name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 551, in _load_from_module_spec
    raise discord.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'cmds.music' raised an error: ValidationError: Name of a chat input command must be lowercase.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 882, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 910, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 182, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ExtensionFailed: Extension 'cmds.music' raised an error: ValidationError: Name of a chat input command must be lowercase.

### Intents

member

### System Information

- Python v3.9.8-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4473+g6b1822ee
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
This is a discord bug.

**Comment by penggin** [comment]
Like a picture above, It's possible on discord API
I think it is a matter with `<str>.islower()` return False when the string is not starts with english.

**Comment by Lulalaby** [comment]
Kk. Still I remember some discussions that non English names are not really stable.

Setting this to low prio for now.

**Comment by penggin** [comment]
That'll do, Thx!

**Comment by BobDotCom** [comment]
![Screen Shot 2021-12-02 at 11 07 39 AM](https://user-images.githubusercontent.com/71356958/144469376-b2ebcd92-164d-40ca-b59e-ed9ad800d7e8.png)
Made a patch, should be merged soon.
