### ISSUE TITLE
Reading default avatar Assets as JPGs fails

### ISSUE THREAD

**Issue by toBeOfUse** [Pycord-Development/pycord#514]
### Summary

Using the User.display_avatar property to retrieve an Asset and then changing that asset's format to JPG results in an Asset that cannot be read

### Reproduction Steps

In a method that was called with a `user` parameter of type `discord.User`, I called `user.display_avatar.replace(size=ceil_size, format="jpg")` and tried to `.read()` the result. This resulted in a crash. The URL of the asset that this `.replace` call generated was https://cdn.discordapp.com/embed/avatars/2.jpg, which I can't access in my browser either. The inability to fetch default user avatars as JPGs appears to be an inherent Discord limitation, so it's not immediately clear what fix to go with, but I think it should at least be noted in the documentation that calls to `.replace` (and `.with_format`) can result in invalid assets in this case, which is highly non-obvious imo.

### Expected Results

Receiving a JPG version of a Discord avatar

### Actual Results

```
Traceback (most recent call last):
  File "C:\Users\Extreme PC\.virtualenvs\mitchbot-YqVhPTxY\lib\site-packages\discord\commands\commands.py", line 84, in wrapped
    ret = await coro(arg)
  File "C:\Users\Extreme PC\.virtualenvs\mitchbot-YqVhPTxY\lib\site-packages\discord\commands\commands.py", line 530, in _invoke
    await self.callback(ctx, **kwargs)
  File "C:\Users\Extreme PC\Code\mitchbot\responders.py", line 164, in start_fight
    file=discord.File(fp=await _fight([fighter1, fighter2]), filename="fight.png")
  File "C:\Users\Extreme PC\Code\mitchbot\responders.py", line 130, in _fight
    i2 = await bot.get_avatar_small(fighters[1], 180)
  File "C:\Users\Extreme PC\Code\mitchbot\MitchBot.py", line 28, in get_avatar_small
    ceil_size_avatar = await user.display_avatar.with_size(ceil_size).with_format("jpg").read()
  File "C:\Users\Extreme PC\.virtualenvs\mitchbot-YqVhPTxY\lib\site-packages\discord\asset.py", line 77, in read
    return await self._state.http.get_from_cdn(self.url)
  File "C:\Users\Extreme PC\.virtualenvs\mitchbot-YqVhPTxY\lib\site-packages\discord\http.py", line 363, in get_from_cdn
    raise Forbidden(resp, 'cannot retrieve asset')
discord.errors.Forbidden: 403 Forbidden (error code: 0): cannot retrieve asset
```

### Intents

I am not passing a discord.Intents class to my client.

### System Information

- Python v3.9.1-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4478+g8e2c6959
- aiohttp v3.8.1
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
Yes this is a discord limitation

**Comment by Lulalaby** [comment]
You might want to check for a 403 and change it to png then
