### ISSUE TITLE
TypeError: 'SlashCommand' object does not support item assignment

### ISSUE THREAD

**Issue by TanjimReza** [Pycord-Development/pycord#545]
### Summary

Cannot use anything inside slash commands

### Reproduction Steps

Use any assignment inside slash commands or events

### Minimal Reproducible Code

```python
bot = discord.Bot(intents=discord.Intents.all())
@bot.event
async def on_ready():
    activity = discord.Activity(type=discord.ActivityType.listening, name="Music")
    await bot.change_presence(status=discord.Status.online, activity=activity)
    queue = {}
    for guild in bot.guilds:
        queue[guild.name] = []
```

### Expected Results

Queue with all the guild names as keys

### Actual Results

Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "d:\test\main.py", line 88, in on_ready
    queue[guild.name] = []
TypeError: 'SlashCommand' object does not support item assignment

### Intents

intents=discord.Intents.all()

### System Information

- Python v3.9.6-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4501+g9fceff87
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

It was working, but suddenly not anymore. I have uninstalled & installed several times but did not work.

**Comment by TanjimReza** [comment]
FIXED!
