### ISSUE TITLE
cog_check not working

### ISSUE THREAD

**Issue by philskillz-coder** [Pycord-Development/pycord#592]
### Summary

cog_check is not invoked

### Reproduction Steps

1. Create a bot as usual
2. Create a cog with a cog_check (wich returns False) and some commands (slash/user/message)
3. Start the bot with the cog you just created
4. Invoke the commands you created

### Minimal Reproducible Code

```python
# main.py
from discord.ext import commands

bot = commands.Bot()
bot.load_cog("cogs.cog_1")

bot.run("TOKEN")

# cogs.cog_1.py
import discord
from discord import commands
from discord.ext import commands as _commands

class Test(_commands.Cog):
    def __init__(self, client: _commands.Bot) -> None:
        super().__init__(client)

    async def cog_check(self, ctx: commands.ApplicationContext) -> bool:
        return False

    @commands.user_command(name="ucmd", guild_ids=[857970291819937802])
    async def _user_command(self, ctx: commands.ApplicationContext, user: discord.Member):
        await ctx.respond("ucmd")

    @commands.message_command(name="mcmd", guild_ids=[857970291819937802])
    async def _message_command(self, ctx: commands.ApplicationCommand, message: discord.Message):
        await ctx.respond("mcmd")

    @commands.slash_command(name="scmd", guild_ids=[857970291819937802])
    async def _slash_command(self, ctx: commands.ApplicationCommand):
        await ctx.respond("scmd")

def setup(client: _commands.Bot):
    client.add_cog(Test(client))
```

### Expected Results

All the commands should not be invoked because the cog_check returns False

### Actual Results

The cog check did not got invoked -> the commands worked

### Intents

None

### System Information

PS C:\Users\Philskillz\Documents\GitHub\WSG-Discord> python -m discord -v 
Traceback (most recent call last):
  File "C:\Users\Philskillz\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Philskillz\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Philskillz\Documents\GitHub\WSG-Discord\discord\__main__.py", line 303, in <module>
    main()
  File "C:\Users\Philskillz\Documents\GitHub\WSG-Discord\discord\__main__.py", line 300, in main
    args.func(parser, args)
  File "C:\Users\Philskillz\Documents\GitHub\WSG-Discord\discord\__main__.py", line 55, in core
    show_version()
  File "C:\Users\Philskillz\Documents\GitHub\WSG-Discord\discord\__main__.py", line 44, in show_version
    pkg = pkg_resources.get_distribution('py-cord')
  File "C:\Users\Philskillz\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 466, in get_distribution
    dist = get_provider(dist)
  File "C:\Users\Philskillz\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 342, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\Users\Philskillz\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\Philskillz\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'py-cord' distribution was not found and is required by the application

OS: Windows 10
Python version: 3.9.5
Installed pycord version: Newest one from GitHub (20.12.2021)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by timmypidashev** [comment]
I didn't even know this was a feature. Gonna test for myself though...

**Comment by Bimi05** [comment]
You're not invoking the check anywhere, you should most likely include a ``checks=[cog_check]`` in the ``@slash_command()`` decorators to allow the invocation of the check
