### ISSUE TITLE
Pycord spits out an error with the import.

### ISSUE THREAD

**Issue by kidney-bean** [Pycord-Development/pycord#608]
### Summary

Pycord spits out a big error with the import.

### Reproduction Steps

Install the alpha version
Import pycord

### Minimal Reproducible Code

```python
import discord
```

### Expected Results

It should import perfectly fine.

### Actual Results

It gave an error.

### Intents

All intents

### System Information

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/async_.py", line 49, in <module>
    from ..channel import PartialMessageable
ImportError: cannot import name 'PartialMessageable' from 'discord.channel' (/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/channel.py)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment]
Reinstalling should help
