### ISSUE TITLE
'Option' object has no attribute '_parameter_name'

### ISSUE THREAD

**Issue by plun1331** [Pycord-Development/pycord#680]
### Summary

The `Option` object doesn't have the `_parameter_name` attribute when initialized manually on a command, instead of as a typehint.

### Reproduction Steps

1. Make command
2. Set options in command decorator (may also work with the `@option` decorator)
3. Run command

### Minimal Reproducible Code

```python
@commands.command(
        name='votes',
        description="Displays the top voters of the month.",
        options=[
            discord.Option(
                SlashCommandOptionType.user,
                name='user',
                description="The user to view the votes for.",
                required=False,
                default=None,
            ),
        ]
    )
    async def votes(self, ctx: AppContext, *, user: typing.Union[discord.Member, discord.User] = None):
        ...
```

### Expected Results

Command work

### Actual Results

```py
Traceback (most recent call last):
  File "/root/enviroments/DiscordBot/events/appcmd_errorhandler.py", line 497, in on_application_command_error
    raise error
  File "/usr/local/lib/python3.8/dist-packages/discord/commands/commands.py", line 97, in wrapped
    ret = await coro(arg)
  File "/usr/local/lib/python3.8/dist-packages/discord/commands/commands.py", line 612, in _invoke
    kwargs[op._parameter_name] = arg
AttributeError: 'Option' object has no attribute '_parameter_name'
```

### Intents

Default + Members

### System Information

```
- Python v3.8.10-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4747+g46e30149
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Could be fixed by having the `_parameter_name` attr default to the option name, but I'm not sure if this is the best solution.

**Comment by plun1331** [comment]
Duplicate of #555 (oops)
