### ISSUE TITLE
The specified component exceeds the maximum width

### ISSUE THREAD

**Issue by yi6dev** [Pycord-Development/pycord#800]
### Summary

In components.0.components.1: The specified component exceeds the maximum width

### Reproduction Steps

View
```python
class ImgView(discord.ui.View):
    def __init__(self, author):
        super().__init__()
        self.timeout = 60
        self.value = None
        self.author = author

    @discord.ui.button(label="Пожаловатся", style=discord.ButtonStyle.red, emoji="<a:oneechanred:931865360418865172>", row=1)
    async def __report(
        self, button: discord.ui.Button, interaction: discord.Interaction
    ):
        if interaction.user == self.author:
            self.value = "report"

    @discord.ui.button(label="Вперед", style=discord.ButtonStyle.green, emoji="<a:oneechangreen:931864919916285962>", row=1)
    async def __next(
        self, button: discord.ui.Button, interaction: discord.Interaction
    ):
        if interaction.user == self.author:
            self.value = "next"
```

In command
```python
view = ImgView(ctx.author)
await ctx.edit(embed=embed, view=view)
```

### Minimal Reproducible Code

```python
Traceback (most recent call last):
  File "C:\Users\cxldx\Documents\GitHub\Oneechan\venv\lib\site-packages\discord\bot.py", line 512, in process_application_commands
    await ctx.command.invoke(ctx)
  File "C:\Users\cxldx\Documents\GitHub\Oneechan\venv\lib\site-packages\discord\commands\core.py", line 261, in invoke
    await injected(ctx)
  File "C:\Users\cxldx\Documents\GitHub\Oneechan\venv\lib\site-packages\discord\commands\core.py", line 100, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.1: The specified component exceeds the maximum width
```

### Expected Results

correctly edit msg

### Actual Results

maximum width error

### Intents

0

### System Information

2.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by yi6dev** [comment]
Before changing to a new view, reset the old one.

Example
```python
await ctx.edit(embed=embed, view=None)
await ctx.edit(embed=embed, view=view)
```
