### ISSUE TITLE
Error on startup when importing pycord version 2.0

### ISSUE THREAD

**Issue by gondilon** [Pycord-Development/pycord#840]
### Summary

Bot throws an error when hitting the import Discord sta

### Reproduction Steps

Import Discord.
Then started bot.

### Minimal Reproducible Code

```python
import discord
```

### Expected Results

Bot starts.

### Actual Results

I Am getting this errror when trying to start my bot. (I just re-installed the development version of pycord in a new venv) . SEems to come from this line:
```py
import discord
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/carl/cloud_files/programming/Discord_bot/venv/venv-linux/lib/python3.10/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/home/carl/cloud_files/programming/Discord_bot/venv/venv-linux/lib/python3.10/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/home/carl/cloud_files/programming/Discord_bot/venv/venv-linux/lib/python3.10/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/home/carl/cloud_files/programming/Discord_bot/venv/venv-linux/lib/python3.10/site-packages/discord/webhook/async_.py", line 49, in <module>
    from ..channel import PartialMessageable
ImportError: cannot import name 'PartialMessageable' from 'discord.channel' (/home/carl/cloud_files/programming/Discord_bot/venv/venv-linux/lib/python3.10/site-packages/discord/channel.py)```

### Intents

Discord.intents.all

### System Information

python -m discord -v
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/carl/cloud_files/programming/Discord_bot/venv/venv-linux/lib/python3.10/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/home/carl/cloud_files/programming/Discord_bot/venv/venv-linux/lib/python3.10/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/home/carl/cloud_files/programming/Discord_bot/venv/venv-linux/lib/python3.10/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/home/carl/cloud_files/programming/Discord_bot/venv/venv-linux/lib/python3.10/site-packages/discord/webhook/async_.py", line 49, in <module>
    from ..channel import PartialMessageable
ImportError: cannot import name 'PartialMessageable' from 'discord.channel' (/home/carl/cloud_files/programming/Discord_bot/venv/venv-linux/lib/python3.10/site-packages/discord/channel.py)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
Make sure you've uninstalled discord.py, and then re-install pycord.

**Comment by gondilon** [comment]
Issue resolved.
