### ISSUE TITLE
on_command_error raises CommandInvokeError instead of MissingPermissions

### ISSUE THREAD

**Issue by Nekidev** [Pycord-Development/pycord#904]
### Summary

on_command_error error handler raises CommandInvokeError instead of MissingPermissions

### Reproduction Steps

cog.py
```python3
from utils.cog import MyCog
from discord.ext import commands
import discord

class SomeRandomCog(MyCog):
    @commands.command()
    async def ban(self, ctx, member: discord.Member):
        await member.ban(reason="No reason")

    @MyCog.listener('on_command_error')
    async def on_command_error(self, ctx, error):
        if isinstance(error, commands.MissingPermissions) or isinstance(error, discord.errors.Forbidden):
            embed = discord.Embed(title="Missing permissions", description="You don't have permission to do this.", color=palette.ERROR)
            embed.set_footer(text=ctx.author.name, icon_url=ctx.author.avatar.url)
            await ctx.send(embed=embed)
        else:
            print(type(error)) 
            raise error
```

utils/cog.py
```python3
from discord.ext import commands
class MyCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
```

Output
```
<class 'discord.ext.commands.errors.CommandInvokeError'>
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "c:\libpath\discord\ext\commands\core.py", line 179, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\projectpath\usecases\moderation\cog.py", line 20, in ban
    await member.ban(reason=reason if reason != None else 'No reason')
  File "c:\libpath\discord\member.py", line 640, in ban
    await self.guild.ban(self, reason=reason, delete_message_days=delete_message_days)
  File "c:\libpath\discord\guild.py", line 2690, in ban
    await self._state.http.ban(user.id, self.id, delete_message_days, reason=reason)
  File "c:\libpath\discord\http.py", line 332, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\libpath\discord\client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "c:\projectpath\usecases\moderation\cog.py", line 251, in on_command_error
    raise error
  File "c:\libpath\discord\ext\commands\bot.py", line 335, in invoke
    await ctx.command.invoke(ctx)
  File "c:\libpath\discord\ext\commands\core.py", line 916, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "c:\libpath\discord\ext\commands\core.py", line 188, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```

### Minimal Reproducible Code

```python
class SomeCog(commands.Cog):
    @commands.Cog.listener('on_command_error')
    async def on_command_error(self, ctx, error):
        if isinstance(error, commands.MissingPermissions) or isinstance(error, discord.errors.Forbidden):
            await ctx.send("Missing permissions")
        else:
            raise error
```

### Expected Results

A message would send to the channel where the command was executed saying "Missing permissions" (in the minimal reproducible code) or an error embed because the error passed as an argument to the function would be `MissingPermissions`.

### Actual Results

An error is still raised because the error type is `discord.ext.commands.errors.CommandInvokeError` and no message or embed is sent

### Intents

discord.Intents.all()

### System Information

- Python v3.10.2-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The actual installed pycord version is 2.0.0

**Comment by plun1331** [comment]
This is the intended behavior, you can unpack the error with `getattr`.

**Comment by Middledot** [comment]
`commands.MissingPermissions` is raised when the command has a `@commands.has_permissions(...)` check, and it is passed into `on_command_error` directly.

`discord.errors.Forbidden` however is raised because the bot didn't have permission to ban the member but still tried to. This is not directly passed to `on_command_error` because it's an API error, not a check/ext.commands related error, so `CommandInvokeError` is passed instead, and as said above, with the `original` attribute containing the actual error.
