### ISSUE TITLE
Error in on_interaction while processing commands.

### ISSUE THREAD

**Issue by JavaProgswing** [Pycord-Development/pycord#912]
### Summary

The bug happens when the bot tries to add slash cmds in process_application_commands.

### Reproduction Steps

I didn't perform any specific steps to encounter that bug, rather got the bug when the slash cmds were being added.

```
Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.9/site-packages/discord/client.py", line 352, in _run_event
   await coro(*args, **kwargs)
   File "/app/.heroku/python/lib/python3.9/site-packages/discord/bot.py", line 1041, in on_interaction
    await self.process_application_commands(interaction)
 File "/app/.heroku/python/lib/python3.9/site-packages/discord/bot.py", line 746, in process_application_commands
  await self.sync_commands()
  File "/app/.heroku/python/lib/python3.9/site-packages/discord/bot.py", line 540, in sync_commands
registered_commands = await self.register_commands(commands, force=force)
 File "/app/.heroku/python/lib/python3.9/site-packages/discord/bot.py", line 419, in register_commands
2022-02-04T03:40:03.327333+00:00 app[worker.1]:     desynced = await self.get_desynced_commands(guild_id=guild_id)
 File "/app/.heroku/python/lib/python3.9/site-packages/discord/bot.py", line 285, in get_desynced_commands
cmd_vals = [val.get(opt, MISSING) for val in as_dict[check]]
KeyError: 'options'
```

### Minimal Reproducible Code

```python
@client.slash_command()
async def ping(ctx):
    await ctx.respond("pong!")
```

### Expected Results

The slash cmd/cmds should have been added successfully

### Actual Results

I got KeyError: 'options' and KeyError: '910522641604042782'.

### Intents

discord.Intents.all()

### System Information

<img width="538" alt="image" src="https://user-images.githubusercontent.com/69581225/152469933-036c60e2-166d-4eb7-a847-9e5d47e70706.png">

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment]
Fixed by 1fb5c0dbcfe935a9467078617c5567601b30e33d

**Comment by good-live** [comment]
I still get this error, with the latest commit from master.

**Comment by Revnoplex** [comment]
same

**Comment by UP929312** [comment]
This was fixed right? On the 5th?
https://github.com/Pycord-Development/pycord/pull/941

**Comment by Revnoplex** [comment]
it appears to be

**Comment by UP929312** [comment]
@Lulalaby You wanna close this?
@JavaProgswing or you
