### ISSUE TITLE
The Slash_cog_group example wont work

### ISSUE THREAD

**Issue by pogrammar** [Pycord-Development/pycord#913]
### Summary

So I used this example: https://github.com/Pycord-Development/pycord/blob/master/examples/app_commands/slash_cog_groups.py, my code is below, the example wont work.

### Reproduction Steps

I followed the example to make it happen :/ below is the code:

The code: 

```python
help = SlashCommandGroup(name="help", description="help")      

class helpcommand(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
    
    
    @help.command(guild_ids=[918748880705839105])
    async def moderation(self, ctx):
        e1 = discord.Embed(title="Moderation", description="Below are the Mod commands:\n `clear`, `kick`, `ban`, `unban`, `mute`, `unmute`, `membercount`,       `poll`")
    
        await ctx.respond(embed=e1)
    
    @help.command(guild_ids=[918748880705839105])
    async def fun(self, ctx):
    
        e2 = discord.Embed(title="Fun commands", description="Below are the Fun commands:\n `eightball`, `hotcalc`")
    
        await ctx.respond(embed=e2)
    
    
    bot.add_application_command(help)    
```

### Expected Results

I wanted it to make a Slash command group, but the above error :/

### Actual Results

Error happened :/

`
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/.local/lib/python3.8/site-packages/discord/bot.py", line 758, in on_connect
    await self.register_commands()
  File "/home/container/.local/lib/python3.8/site-packages/discord/bot.py", line 341, in register_commands
    cmd = find(lambda cmd: cmd.name == i["name"] and cmd.type == i["type"] and int(i["guild_id"]) in cmd.guild_ids, self.pending_application_commands)
  File "/home/container/.local/lib/python3.8/site-packages/discord/utils.py", line 401, in find
    if predicate(element):
  File "/home/container/.local/lib/python3.8/site-packages/discord/bot.py", line 341, in <lambda>
    cmd = find(lambda cmd: cmd.name == i["name"] and cmd.type == i["type"] and int(i["guild_id"]) in cmd.guild_ids, self.pending_application_commands)
TypeError: argument of type 'NoneType' is not iterable
`
[.](https://github.com/Pycord-Development/pycord/issues/913#issuecomment-1029619087)

### Intents

discord.Intents.all()

### System Information

I'm using the latest version, and I'm coding it in a pterodactyl host I use

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by plun1331** [comment]
formatted traceback correctly:
```py
Traceback (most recent call last): 
File "/home/container/.local/lib/python3.8/site-packages/discord/client.py", line 352, in _run_event 
    await coro(*args, **kwargs) 
File "/home/container/.local/lib/python3.8/site-packages/discord/bot.py", line 758, in on_connect 
    await self.register_commands() 
File "/home/container/.local/lib/python3.8/site-packages/discord/bot.py", line 341, in register_commands 
    cmd = find(lambda cmd: cmd.name == i["name"] and cmd.type == i["type"] and int(i["guild_id"]) in cmd.guild_ids, self.pending_application_commands) 
File "/home/container/.local/lib/python3.8/site-packages/discord/utils.py", line 401, in find 
    if predicate(element): 
File "/home/container/.local/lib/python3.8/site-packages/discord/bot.py", line 341, in <lambda> 
    cmd = find(lambda cmd: cmd.name == i["name"] and cmd.type == i["type"] and int(i["guild_id"]) in cmd.guild_ids, self.pending_application_commands) 
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by pogrammar** [comment]
Why isnt this closed yet ;-;
