### ISSUE TITLE
2.0.0b3 register_commands() error on start

### ISSUE THREAD

**Issue by dnlldl** [Pycord-Development/pycord#942]
### Summary

2.0.0b3 register_commands() error on start

### Reproduction Steps

I updated from 2.0.0b1 to 2.0.0b3 and the error started to happen. I didn't do any further tests so far, I use cogs with commands, slash commands, listeners and tasks altogether.

### Expected Results

No error

### Actual Results

`on_error()` is fired when the bot starts, here is the full traceback:

	Traceback (most recent call last):
	  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 352, in _run_event
		await coro(*args, **kwargs)
	  File "/usr/local/lib/python3.9/site-packages/discord/bot.py", line 1038, in on_connect
		await self.sync_commands()
	  File "/usr/local/lib/python3.9/site-packages/discord/bot.py", line 540, in sync_commands
		registered_commands = await self.register_commands(commands, force=force)
	  File "/usr/local/lib/python3.9/site-packages/discord/bot.py", line 382, in register_commands
		commands = copy.deepcopy(commands)
	  File "/usr/lib64/python3.9/copy.py", line 146, in deepcopy
		y = copier(x, memo)
	  File "/usr/lib64/python3.9/copy.py", line 205, in _deepcopy_list
		append(deepcopy(a, memo))
	  File "/usr/lib64/python3.9/copy.py", line 172, in deepcopy
		y = _reconstruct(x, memo, *rv)
	  File "/usr/lib64/python3.9/copy.py", line 270, in _reconstruct
		state = deepcopy(state, memo)
	  File "/usr/lib64/python3.9/copy.py", line 146, in deepcopy
		y = copier(x, memo)
	  File "/usr/lib64/python3.9/copy.py", line 230, in _deepcopy_dict
		y[deepcopy(key, memo)] = deepcopy(value, memo)
	  File "/usr/lib64/python3.9/copy.py", line 172, in deepcopy
		y = _reconstruct(x, memo, *rv)
	  File "/usr/lib64/python3.9/copy.py", line 270, in _reconstruct
		state = deepcopy(state, memo)
	  File "/usr/lib64/python3.9/copy.py", line 146, in deepcopy
		y = copier(x, memo)
	  File "/usr/lib64/python3.9/copy.py", line 230, in _deepcopy_dict
		y[deepcopy(key, memo)] = deepcopy(value, memo)
	  File "/usr/lib64/python3.9/copy.py", line 172, in deepcopy
		y = _reconstruct(x, memo, *rv)
	  File "/usr/lib64/python3.9/copy.py", line 270, in _reconstruct
		state = deepcopy(state, memo)
	  File "/usr/lib64/python3.9/copy.py", line 146, in deepcopy
		y = copier(x, memo)
	  File "/usr/lib64/python3.9/copy.py", line 230, in _deepcopy_dict
		y[deepcopy(key, memo)] = deepcopy(value, memo)
	  File "/usr/lib64/python3.9/copy.py", line 172, in deepcopy
		y = _reconstruct(x, memo, *rv)
	  File "/usr/lib64/python3.9/copy.py", line 270, in _reconstruct
		state = deepcopy(state, memo)
	  File "/usr/lib64/python3.9/copy.py", line 146, in deepcopy
		y = copier(x, memo)
	  File "/usr/lib64/python3.9/copy.py", line 230, in _deepcopy_dict
		y[deepcopy(key, memo)] = deepcopy(value, memo)
	  File "/usr/lib64/python3.9/copy.py", line 172, in deepcopy
		y = _reconstruct(x, memo, *rv)
	  File "/usr/lib64/python3.9/copy.py", line 270, in _reconstruct
		state = deepcopy(state, memo)
	  File "/usr/lib64/python3.9/copy.py", line 146, in deepcopy
		y = copier(x, memo)
	  File "/usr/lib64/python3.9/copy.py", line 230, in _deepcopy_dict
		y[deepcopy(key, memo)] = deepcopy(value, memo)
	  File "/usr/lib64/python3.9/copy.py", line 172, in deepcopy
		y = _reconstruct(x, memo, *rv)
	  File "/usr/lib64/python3.9/copy.py", line 270, in _reconstruct
		state = deepcopy(state, memo)
	  File "/usr/lib64/python3.9/copy.py", line 146, in deepcopy
		y = copier(x, memo)
	  File "/usr/lib64/python3.9/copy.py", line 230, in _deepcopy_dict
		y[deepcopy(key, memo)] = deepcopy(value, memo)
	  File "/usr/lib64/python3.9/copy.py", line 161, in deepcopy
		rv = reductor(4)
	TypeError: cannot pickle '_asyncio.Task' object

### Intents

discord.Intents.all()

### System Information

	vm-dev:~ # python3.9 -m discord -v
	- Python v3.9.6-final
	- py-cord v2.0.0-beta
		- py-cord pkg_resources: v2.0.0b3
	- aiohttp v3.7.4.post0
	- system info: Linux 5.3.18-59.40-default #1 SMP Mon Jan 3 18:43:20 UTC 2022 (34edd9c)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by EmreTech** [comment]
Maybe try beta 4?

**Comment by Revnoplex** [comment]
beta 4 has another problem, but I think its now fixed on the latest commit
