### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by PythonIntermediateCoder** [Pycord-Development/pycord#978]
### Summary

There's an error that have raised when I use the `ext.commands.DefaultHelpCommand`.

### Reproduction Steps

1. Make a normal help command.
2. Type the help command with no arguments to invoke the `send_bot_help` function.

### Minimal Reproducible Code

```python
from discord.ext.commands import Bot, DefaultHelpCommand

bot = Bot(command_prefix=..., intents=..., help_command=DefaultHelpCommand())
```

### Expected Results

The exception raised should not raise when I invoke the help command. But the exception doesn't raise when I invoke cog help, group help or a command help.

### Actual Results

```py
Traceback (most recent call last):
  File "/home/usr/lib/python3.8/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/bot/utils/bot.py", line 77, in on_command_error
    raise error
  File "/home/usr/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 335, in invoke
    await ctx.command.invoke(ctx)
  File "/home/usr/lib/python3.8/site-packages/discord/ext/commands/core.py", line 916, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/usr/lib/python3.8/site-packages/discord/ext/commands/core.py", line 188, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
```

### Intents

`messages`

### System Information

- Python v3.8.0-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Linux 3.10.72 #1 SMP PREEMPT Mon Mar 27 10:50:45 CST 2017

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I ran the bot on an old Linux machine with the given information, and the exception raises whenever I invoke the `DefaultHelpCommand.send_bot_help`.

**Comment by PythonIntermediateCoder** [comment]
The issue only happens when the package has been installed incorrectly.
